### ISSUE TITLE
Is it possible to create animation using the designer if yes how

### ISSUE THREAD

**Issue by SaptakBhoumik** [ParthJadhav/Tkinter-Designer#10]

**Comment by ParthJadhav** [comment]
No, It’s not possible to create animation using Tkinter Designer. 
But What are you trying to do ? Sounds interesting

**Comment by SaptakBhoumik** [comment]
@ParthJadhav Actually I am working on a project and has a lot of animation but I am not so good at making animation so I was thinking of using this designer to create the animation. But anyways this is a great tool
