### ISSUE TITLE
Assets folder not generated

### ISSUE THREAD

**Issue by tridox25** [ParthJadhav/Tkinter-Designer#101]
Hi! I'm trying to generate a file but my assets folder is empty.

This is the error:
```
Creating Element { name: Frame 1, type: FRAME }
Element with the name: `Frame 1` cannot be parsed. Would be displayed as Black Rectangle
```

Here is the link to my figma design: [https://www.figma.com/file/8rZwC9OAJbugW7sG48ygvJ/Fitness-dashboard-Community?node-id=0%3A1](https://www.figma.com/file/8rZwC9OAJbugW7sG48ygvJ/Fitness-dashboard-Community?node-id=0%3A1)

**Comment by ParthJadhav** [comment]
The type of UI you have created seems to have been copied from a different source. And it wont work as Tkinter Designer Functions on Naming of the elements. 

Please read the instructions carefully and then create a simple UI to understand it and then start to build up on it.

**Comment by ParthJadhav** [comment]
Closing the issue because you did not read the instructions. Feel free to reopen if you face any problems after you have read the instructions.
