### ISSUE TITLE
Edit Rectangles Sizes/ Text Values in python

### ISSUE THREAD

**Issue by Vinyzu** [ParthJadhav/Tkinter-Designer#112]
I think its self explainitory if i say if this would be possible?
https://www.figma.com/file/f6RWVRQx4TNfn8gh5bXjPb/Untitled?node-id=0%3A1
I would have to edit the size of the rectangles due to values...

**Comment by ParthJadhav** [comment]
I did not get what you meant but I checked the file and it had incorrect naming and groups.

**Comment by Vinyzu** [comment]
Yes i just wanna know if i can edit the size of rectangles in python

**Comment by ParthJadhav** [comment]
Sorry for late response. 

Yes you can edit the size.

**Comment by Vinyzu** [comment]
ok thanks!
