### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by Vinyzu** [ParthJadhav/Tkinter-Designer#115]
https://www.figma.com/file/E2TA4V9Ck3k2xZ06uXrMaa/Material-Design-Desktop-Kit-for-Figma-Free-Edition-Copy?node-id=0%3A1
So i have a image like this ^^, but when i run the designer it just doesnt creates this image

**Comment by ParthJadhav** [comment]
You'll need to add a Frame. Read the instructions carefully.

Also you'll need to name it "Image".

**Comment by Vinyzu** [comment]
I still dont get what i did wrong tbh, i have a frame and a Grou called "Image"...?

**Comment by ParthJadhav** [comment]
Can you share the output of the Command line?

**Comment by Vinyzu** [comment]
theres none, no error or whatsoever

**Comment by ParthJadhav** [comment]
What are you running?

**Comment by Vinyzu** [comment]
The Tkinter Designer? lol
windows 10

**Comment by Vinyzu** [comment]
hello? :/

**Comment by ParthJadhav** [comment]
Command, I said.

**Comment by Vinyzu** [comment]
Command? You mean to start tkinter designer or what?

**Comment by ParthJadhav** [comment]
Yes, to start tkinter designer.

**Comment by Vinyzu** [comment]
im using atom to run the script

**Comment by Vinyzu** [comment]
let me try with cmd

**Comment by Vinyzu** [comment]
same with cmd and "python tkinter_designer.py"

**Comment by ParthJadhav** [comment]
You are using a old version

**Comment by ParthJadhav** [comment]
Clone the latest version and read the latest instructions.

You are using a old version and reading the latest instructions 😅

**Comment by Vinyzu** [comment]
now i get
el_r = element["fills"][0]["color"]['r'] * 255
IndexError: list index out of range

**Comment by Vinyzu** [comment]
but still not generating a image

**Comment by Vinyzu** [comment]
Im using the "master" branch...

**Comment by ParthJadhav** [comment]
Can you tell me now how are you running the code?

**Comment by Vinyzu** [comment]
now with atom again?

**Comment by ParthJadhav** [comment]
No, with CMD.

**Comment by Vinyzu** [comment]
oh imma try with "python tkinter_designer.py"

**Comment by Vinyzu** [comment]
still no image

**Comment by ParthJadhav** [comment]
I said that clone the latest repo then read the instructions. You are doing it wrong!

**Comment by Vinyzu** [comment]
ok, i cloned the repo, cd into gui, and ran gui, did everything as i should, still no image

**Comment by Vinyzu** [comment]
so?

**Comment by Vinyzu** [comment]
hello?

**Comment by ParthJadhav** [comment]
> ok, i cloned the repo, cd into gui, and ran gui, did everything as i should, still no image

What output is shown in CMD?

**Comment by Vinyzu** [comment]
no output, it also says "files created successfully", or smthng like that, what i wanna sayy, theres a success message...

**Comment by saur0x** [comment]
> no output, it also says "files created successfully", or smthng like that, what i wanna sayy, theres a success message...

Can you paste here the full success message?
