### ISSUE TITLE
Cannot open tkinter designer after install

### ISSUE THREAD

**Issue by brockally** [ParthJadhav/Tkinter-Designer#116]
I get the error below when trying to open tkinter designer. Any ideas what's gone wrong?

~/Tkinter-Designer/gui $ python3 gui.py
Traceback (most recent call last):
  File "gui.py", line 13, in <module>
    from tkdesigner.designer import Designer
  File "/home/pi/Tkinter-Designer/tkdesigner/designer.py", line 2, in <module>
    from tkdesigner.figma.frame import Frame
  File "/home/pi/Tkinter-Designer/tkdesigner/figma/frame.py", line 4, in <module>
    from .node import Node
  File "/home/pi/Tkinter-Designer/tkdesigner/figma/node.py", line 31
    def get(self, key, default=None, /):
                                     ^
SyntaxError: invalid syntax

**Comment by ParthJadhav** [comment]
Please update your Python:)

**Comment by saur0x** [comment]
I think `/` and `*` should be removed from arguments for backward compatibility with older Python versions. I added it for no particular reason other than making the function signature the same as `dict.get` method.

**Comment by ParthJadhav** [comment]
Yes @saur0x 👍🏻 That would be good.

**Comment by MystPi** [comment]
I have the same issue and it doesn't seem to be fixed. Any chance it will be fixed soon? I can't wait to use Tkinter Designer. 😄

**Comment by ParthJadhav** [comment]
It's fixed @MystPi . Please clone the latest version :)
