### ISSUE TITLE
RuntimeError: Tkinter Designer requires internet access to work.

### ISSUE THREAD

**Issue by bermudezjp** [ParthJadhav/Tkinter-Designer#120]
![image](https://user-images.githubusercontent.com/87876672/129239473-1f514169-75f9-483c-9661-be3c17598352.png)

I'm getting this error I clearly have internet access and I followed all the intructions

**Comment by ParthJadhav** [comment]
Hey @saur0x , Can you help him with this ?

**Comment by The-Real-Thisas** [comment]
Connect to the internet? Would it be possible to add more information such as your device specification as well as a full log of the error.

**Comment by ParthJadhav** [comment]
@The-Real-Thisas Thanks for being involved 👍 

@bermudezjp closing this issue since its solved.
