### ISSUE TITLE
No module named tkinter_designer.py

### ISSUE THREAD

**Issue by rzamarefat** [ParthJadhav/Tkinter-Designer#122]
I have followed the instructions in the PDF provided in the repo and noticed that there isn't any module name tkinter_designer.py in the root dir of the repo. However, the instructions found in the fore-mentioned PDF requires two steps after cloning the repo:
1- pip install -r requirements.txt
2- python3 tkinter_designer.py 
The problem lies in the second command.
Am I doing sth wrong?

**Comment by neilbaldwin** [comment]
I haven't checked the PDF but it maybe that the information in there is out of date. Always check the instructions in the repo first:

https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#using-tkinter-designer-top

From here:

https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md
