### ISSUE TITLE
Where is the file gone?

### ISSUE THREAD

**Issue by DiscrimIsPog** [ParthJadhav/Tkinter-Designer#126]
I don't see the file at all. Was it taken down?

**Comment by jrobchin** [comment]
@DiscrimIsPog  The easiest way to use Tkinter Designer is with the CLI packaged with the PyPi package.

See: https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#using-tkinter-designer-top

**Comment by jvendegna** [comment]
@DiscrimIsPog Are you still in need of assistance?

**Comment by jvendegna** [comment]
@DiscrimIsPog 24 hours until I close this issue.
