### ISSUE TITLE
There is no ".exe" file in "Assets" part

### ISSUE THREAD

**Issue by Wang-zhechao** [ParthJadhav/Tkinter-Designer#128]
problem  as title

**Comment by jvendegna** [comment]
Thank you, we're in need of a documentation update. I'll fix. But there will not be an .exe supplied. Instead we developers decided that you need python installed to generate the build directory anyway, so we made [tkdesigner](https://pypi.org/project/tkdesigner/) instead. You can install it directly, or we suggest to use [poetry](https://python-poetry.org/) and simply use the CLI tool.

`tkdesigner <FIGMA_URL> <FIGMA_TOKEN>`
