### ISSUE TITLE
extra '/' in node.py line 31

### ISSUE THREAD

**Issue by yucongo** [ParthJadhav/Tkinter-Designer#129]
It appears there is an extar `/`  in `tkdesigner\figma\node.py line 31`

Newly cloned repo:
`         def get(self, key, default=None, /):`
Ought to be
`         def get(self, key, default=None):`

I use python 3.7. But I think no matter what version there cant be a `/` there.

**Comment by jvendegna** [comment]
I see it and have a fix in progress, thank you!

**Comment by ParthJadhav** [comment]
This has been fixed ! Thanks for spotting the mistake @yucongo and thanks for making the changes @jvendegna.
