### ISSUE TITLE
Support for the Arabic language

### ISSUE THREAD

**Issue by yamanidev** [ParthJadhav/Tkinter-Designer#138]
Hello, I loved what you did with the project and I would like to contribute to it by adding Arabic translation to the documents.

**Comment by jvendegna** [comment]
Go after it. Fork the repo and open a pull request when you're ready. Many thanks!

**Comment by ParthJadhav** [comment]
Yess ! @yamanidev just create a pull request when you are ready.  
Let me know if you need any help. 
Looking forward for the translation 😃

**Comment by yamanidev** [comment]
@ParthJadhav I will haha, I have translated README.md (pushed to my fork), will start working on instructions.md very soon.

**Comment by ParthJadhav** [comment]
That's great @yamanidev ! Keep doing the great work 👏👏

**Comment by yamanidev** [comment]
I've created a pull request: https://github.com/ParthJadhav/Tkinter-Designer/pull/144
