### ISSUE TITLE
White left + top border on click

### ISSUE THREAD

**Issue by Larkify** [ParthJadhav/Tkinter-Designer#139]
1. When I click one of my buttons, the top and left side border of the button go white. I'm not entirely sure why. 
2. I have random white bars around the orange buttons which aren't there on Figma. 

> _White top and left side border_: https://cdn.larkx.xyz/ktvz73kq.gif
> _Random white lines on orange buttons_:  https://cdn.larkx.xyz/ktvza711.png
> _Original figma design_: https://cdn.larkx.xyz/ktvzaxon.png

**Comment by ParthJadhav** [comment]
Use Github to add pictures.

**Comment by Larkify** [comment]
> Same issue here.

I ended up using PyQt instead.
