### ISSUE TITLE
Tkinter-Designer Logo

### ISSUE THREAD

**Issue by ParthJadhav** [ParthJadhav/Tkinter-Designer#14]
Hey @piccoloser, 
Here's the logo for the executable :- 

![aArtboard 1 copy 22x](https://user-images.githubusercontent.com/42001064/120528163-c3402a00-c3f8-11eb-9f1d-120fb9cc850e.png)

Uploaded here for easy access.

**Comment by ParthJadhav** [comment]
Download it later :)

**Comment by piccoloser** [comment]
Oh, haha, I wish I had seen this. I recreated it just now:
![logo](https://user-images.githubusercontent.com/63938746/120530855-f3ada700-c3ab-11eb-88e7-134bdf0cf23e.png)
