### ISSUE TITLE
Wrong position background image

### ISSUE THREAD

**Issue by Qiming-Liu** [ParthJadhav/Tkinter-Designer#143]
![image](https://user-images.githubusercontent.com/68600416/134875601-ea81616d-08a0-4b4b-92c2-98cba7e70a59.png)

image_1.png is the background image of the frame, the expected Y should be half of the width(537) as 268.5.

**Comment by ParthJadhav** [comment]
Can you share the link to your file?

**Comment by ParthJadhav** [comment]
Also can I know what IDE are you using to code?

**Comment by Qiming-Liu** [comment]
IDE is just Jupyter notebook.
I found that the reason for this bug is that the actual size of a single-line text box exceeds the frame.
![image](https://user-images.githubusercontent.com/68600416/135384990-406a971f-912d-4852-8091-497c77e542c0.png)
