### ISSUE TITLE
After reading carefully all the instructions I still get a black Background output.

### ISSUE THREAD

**Issue by Dotolox** [ParthJadhav/Tkinter-Designer#148]
1. Error Message

Creating Element { name: Background, type: GROUP }
Element with the name: `Background` cannot be parsed. Would be displayed as Black Rectangle
Creating Element { name: Button, type: GROUP }
Creating Element { name: TextBox, type: RECTANGLE }
Creating Element { name: TextArea, type: TEXT }
Creating Element { name: TextBox, type: RECTANGLE }
Creating Element { name: TextArea, type: TEXT }
Creating Element { name: TextBox, type: RECTANGLE }
Creating Element { name: TextArea, type: TEXT }
Creating Element { name: TextBox, type: RECTANGLE }
Creating Element { name: TextArea, type: TEXT }
Creating Element { name: TextBox, type: RECTANGLE }
Creating Element { name: TextArea, type: TEXT }

2. Link to the Figma File
https://www.figma.com/file/haMxoppeLJNpQdvKw3l3Qk/Untitled?node-id=0%3A1

**Comment by ParthJadhav** [comment]
I guess it took too long for me to reply.. The fix was easy, Just change the name of Background to -> Image

**Comment by Samrudhi3** [comment]
@ParthJadhav it worked for me Background->Image ...thank you....Now my music player project will rock in college!
