### ISSUE TITLE
Wrong formatting

### ISSUE THREAD

**Issue by slender111223** [ParthJadhav/Tkinter-Designer#153]
I follow all the step and i got this not this. Please help me
![image](https://user-images.githubusercontent.com/79234171/137510744-7ecc05d6-a37b-448b-9b30-3d3c0bab7f58.png)
![image](https://user-images.githubusercontent.com/79234171/137510775-7a47bc15-5cb1-43c9-a36b-30f4643e9eec.png)

**Comment by ParthJadhav** [comment]
Can you share link to your figma file?

**Comment by slender111223** [comment]
I had fix but it's won't work. Please check for me
This is my figma link file

https://www.figma.com/file/1SIMaqNyiwjIo3HIKkuky1/Phi-Hùng-Tạ-Hoàng-s-team-library?node-id=0%3A1
