### ISSUE TITLE
Doesn't work! What to do?

### ISSUE THREAD

**Issue by RazerBean2k18** [ParthJadhav/Tkinter-Designer#161]
It won't work. I've checked the link and the token several times but it doesn't work on my Mac.

**Comment by RazerBean2k18** [comment]
https://www.figma.com/file/JBdgIobNT77PrTDvIPFk9f/Untitled?node-id=0%3A1

**Comment by RazerBean2k18** [comment]
Anything you found?? @ParthJadhav

**Comment by ParthJadhav** [comment]
I haven't tried to convert it yet. My PC is Erased and it will take time to install all the things back as I am out of town. 

Until then try this URL :- 

https://www.figma.com/file/WVLnulVsI177tvnxSdqOUZ/Example-File?node-id=0%3A1

**Comment by ParthJadhav** [comment]
Is it working now?

**Comment by RazerBean2k18** [comment]
Sadly not but I’ve now built it without your script…

**Comment by ParthJadhav** [comment]
Do you want help? Or this is your last project with tkinter?

**Comment by RazerBean2k18** [comment]
It’s not my last project with tainted; it is a great python extension. I am just not going to use your script/plug-in since I’ve figured out an easy way to do it. Still thanks for your help!
