### ISSUE TITLE
RuntimeError: Couldn't add tkdesigner to the PATH. 

### ISSUE THREAD

**Issue by gus123671** [ParthJadhav/Tkinter-Designer#169]
Title. Refer to screenshot. Would appreciate any assistance/advice.
 
![image](https://user-images.githubusercontent.com/52800952/140572412-6f990c7f-b5c6-4136-85f5-727d3ee28428.png)

Thanks.

**Comment by ParthJadhav** [comment]
Can you clone the latest commit and then try to install the requirements again by ->

`pip3 install -r requirements.txt`
