### ISSUE TITLE
_tkinter.TclError: bitmap "images/iconbitmap.ico" not defined _____   Import "backend" could not be resolvedPylancereportMissingImports)

### ISSUE THREAD

**Issue by Shaco74** [ParthJadhav/Tkinter-Designer#17]
like the title says i have the following problems with tkinter_designer.py

1. `import backend` isnt working properlly (atleast vscode is having trouble)

2. if i try to run the script i get to following error message:
```
-->>>python3 tkinter_designer.py
Traceback (most recent call last):
  File "/home/shaco/Tkinter-Designer/tkinter_designer.py", line 55, in <module>
    window.iconbitmap("images/iconbitmap.ico")
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "images/iconbitmap.ico" not defined
```

**Comment by piccoloser** [comment]
For reference, how did you install the program? Using the Git command, or an executable?

**Comment by ParthJadhav** [comment]
Hey @Shaco74 , 
1. I don't use VSCode but what do you mean by 'Isnt working properly' ?
2. I was not able to reproduce this error both on windows and mac.

**Comment by Shaco74** [comment]
Excuse my inaccuracie please. It's my first time reporting something on GitHub. 

So I am running the latest Ubuntu version (hippo)
I installed the program by cloning the git repo and installing the requirements (basically following the installation instructions) 

By saying that VSCode isn't working properly I meant that VSCode is highlighting one specific line in the script. It highlights the 'import backend' line as a missing import error. (this could be a bug of VSCode or pylance because there is not an Error referring to this when running the python script from the terminal.)


Still there is this error comming up 
`_tkinter.TclError: bitmap "images/iconbitmap.ico" not defined`
I am not too experienced with python. But I have this feeling that this error is related to the working directory the script is using. I saw that there were indeed lines which would change the os.dir

Hope I could help you out providing you this informations

**Comment by Shaco74** [comment]
I just tested Tkinter-Designer on my Windows machine, it works fine here.. 
Are there linux distros on which the software got tested on?

**Comment by ParthJadhav** [comment]
Sorry from us too @Shaco74 , Tkinter Designer was never tested on linux machines. I am currently looking for solutions for the problem you've mentioned.

**Comment by Shaco74** [comment]
Yeah i allready tired commenting out that line, but he catched another error which looked very similiar. I assum its just about relative and absolute paths which are causing the trouble here on linux

**Comment by ParthJadhav** [comment]
Can I know the other error ?

**Comment by Shaco74** [comment]
I am not currently on my linux mashine but I am preatty sure it was about 
`generate_btn_img = PhotoImage(file="./images/generate.png")`
similiar error: not able to locate the file

**Comment by ParthJadhav** [comment]
Ohh I see. I'll look into it. Thanks for letting us know.

**Comment by piccoloser** [comment]
Looks like something an import of the `os` module and using `os.path.join()` would fix.

**Comment by Shaco74** [comment]
So i found out that the Scripts wasnt actually having trouble due to relative/absolute paths.
The problem was simply that Linux cant work with .ico files. 

I opened up this pull request here:
https://github.com/ParthJadhav/Tkinter-Designer/pull/21

**Comment by ideprecated** [comment]
The same holds true for macOS, you can work around this issue in the meantime by commenting out line #55 in `tkinter_designer.py`

```
#window.iconbitmap("images/iconbitmap.ico")
```

**Comment by ParthJadhav** [comment]
Yes, Actually I discovered that issue on Mac too but not much alarming as Linux. And the solution is given by @Shaco74 in his pull request. 

Instead of commenting it, we can use GIF. It works on Mac and @Shaco74 is testing it on Windows and Linux.

**Comment by ParthJadhav** [comment]
Fixed issue in the latest commit.

**Comment by braveltd** [comment]
> The same holds true for macOS, you can work around this issue in the meantime by commenting out line #55 in `tkinter_designer.py`
> 
> ```
> #window.iconbitmap("images/iconbitmap.ico")
> ```

THANKS!
