### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ea2' in position 1027: character maps to <undefined>

### ISSUE THREAD

**Issue by thaisonho** [ParthJadhav/Tkinter-Designer#170]
Hi,

I'm trying to use the tool to convert my figma project but keep getting this message in the terminal.

Here's is the full thing that appeared on my screen 
```
Traceback (most recent call last):
  File "C:\msys64\mingw64\lib\python3.9\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\Files\Tkinter-Designer\gui\gui.py", line 72, in btn_clicked
    designer.design()
  File "D:\Files\Tkinter-Designer\tkdesigner\designer.py", line 30, in design
    self.output_path.joinpath(CODE_FILE_NAME).write_text(code)
  File "C:\msys64\mingw64\lib\python3.9\pathlib.py", line 1288, in write_text
    return f.write(data)
  File "C:\msys64\mingw64\lib\python3.9\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u1ea2' in position 1027: character maps to <undefined>
```
Here's my figma link:
https://www.figma.com/file/dpC4gnlcNKtKrLRPfHBKNJ/GiaiPTb2

Thanks for your help.

**Comment by ParthJadhav** [comment]
Tkinter Designer struggles while converting Text from other languages than English... 

You can add English text while converting the design and then add the original text directly to the code.

**Comment by thaisonho** [comment]
@ParthJadhav Thank you for helping me. It works totally fine when I change to English. But I came up with another problem is the corner radius of rectangle couldn't be transformed. Is there any ways to fix it?

Many thanks!

**Comment by ParthJadhav** [comment]
Sadly corner radius is not supported om rectangles. You can change the name of rectangle to "Image" this way it would be rendered as it is.

**Comment by thaisonho** [comment]
My code works fine now, this tool help my school project a lot! Thank you for your help, sir
