### ISSUE TITLE
Fonts appear wrongly when opened tkinter program

### ISSUE THREAD

**Issue by PhurinatFlint** [ParthJadhav/Tkinter-Designer#171]
![image](https://user-images.githubusercontent.com/84864143/143443345-74a2631b-152f-4efc-9b82-fc63673c6c73.png)
![image](https://user-images.githubusercontent.com/84864143/143443948-1fa90fba-f570-412e-aee9-5af5d2c991ad.png)

Looks like in my Figma has set font to 'Roboto', but when i opened the program, It doesn't show the font which set via figma.

1st image is what my program shows
2nd image is what my Figma designed.

**Comment by ParthJadhav** [comment]
The problem would be the font not being installed on your computer. Please check if the font is installed and if not then try installing.
