### ISSUE TITLE
i cant find tkinter designer.py

### ISSUE THREAD

**Issue by DimasNovianAS** [ParthJadhav/Tkinter-Designer#172]
i cant find tkinter designer.py

**Comment by ParthJadhav** [comment]
Sorry @DimasNovianAS , The instructions on the YT video are outdated. Please refer to -> https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md

**Comment by DimasNovianAS** [comment]
Okay thanks a lot...
