### ISSUE TITLE
"No matches found" CLI

### ISSUE THREAD

**Issue by k5kk** [ParthJadhav/Tkinter-Designer#173]
Hello!

I've never reported an issue before, so please forgive any disregard of norms/etiquette.

I am trying to use the tkdesigner CLI. I have successfully installed pip3, tkdesigner, and tried to run
both:

1) $ python -m tkdesigner.cli $FIGMA_URL $FIGMA_TOKEN
2) tkdesigner $FIGMA_URL $FIGMA_TOKEN

I get this back:

<img width="567" alt="Screenshot 2021-12-03 at 15 29 25" src="https://user-images.githubusercontent.com/78740732/144619529-81a55a65-a783-41cf-b663-dc49943d2de5.png">

MacOS Catalina btw, although that is likely not relevant.

**Comment by ParthJadhav** [comment]
Don't worry @k5kk you have reported it correctly. And yes I experienced the same issue too. I would look into it.

Until then you can use the GUI version which is working correctly. 

```
git clone https://github.com/ParthJadhav/Tkinter-Designer.git
cd Tkinter-Designer
cd gui
python3 gui.py
```
