### ISSUE TITLE
can't open tkinter designer after installing it

### ISSUE THREAD

**Issue by Omaralsamahi** [ParthJadhav/Tkinter-Designer#176]
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Anyone has a solution for this?☝️
This happened while I tried opening tkinter designer with this command:
Python3 tkinter_designer.py

**Comment by ParthJadhav** [comment]
You need to properly install python and add it to path for it to function correctly. 
Try 

`python tkinter_designer.py`

or

`py tkinter_designer.py`

**Comment by Anas966** [comment]
Hello!

Where is the tkinter_designer.py file located?

**Comment by devshades-au** [comment]
> Hello!
> 
> Where is the tkinter_designer.py file located?

I've opened a new issue for this.

The closest I could find was in a experimental version branch: https://github.com/ParthJadhav/Tkinter-Designer/tree/version-1.0.0-(Experimental)

**Comment by ParthJadhav** [comment]
Thanks for helping him @devshades-au !
