### ISSUE TITLE
Turkish encoding is not importing properly 

### ISSUE THREAD

**Issue by OlcaytoKorcan** [ParthJadhav/Tkinter-Designer#177]

**Comment by ParthJadhav** [comment]
Yes, Tkinter Designer struggles with other languages than english. Try to add dummy text and then manually update the text after it's converted.

**Comment by OlcaytoKorcan** [comment]
Yes, I have solved this issue. 
If you have any erase turkish character, while converting to tkinter encoding will be cannot be decided properly.
