### ISSUE TITLE
white edges

### ISSUE THREAD

**Issue by nimiology** [ParthJadhav/Tkinter-Designer#178]
I've been working on this :
![image](https://user-images.githubusercontent.com/73313947/147503102-4b540097-ffa4-4f16-9e7f-ca06339def18.png)
but when I get the Tkinter-designer result with the white edges buttons:
![image](https://user-images.githubusercontent.com/73313947/147503216-75c57a29-1b40-4146-858e-4109b930f467.png)

**Comment by ParthJadhav** [comment]
You can have an extra background layer in the button group which matches the background color to avoid that thing.
