### ISSUE TITLE
Windows executable re-upload.

### ISSUE THREAD

**Issue by piccoloser** [ParthJadhav/Tkinter-Designer#18]
Re-uploading the executable for Windows. We'll have to add a disclaimer to the README that lets users know about the Windows Defender thing.

[Further reading on StackOverflow](https://stackoverflow.com/questions/44377666/pyinstaller-exe-throws-windows-defender-no-publisher)

[tkinter_designer-Windows.zip](https://github.com/ParthJadhav/Tkinter-Designer/files/6609618/tkinter_designer-Windows.zip)

**Comment by ParthJadhav** [comment]
Added it in the release, Thanks for it !
