### ISSUE TITLE
Request for another example to the README

### ISSUE THREAD

**Issue by Just-Moh-it** [ParthJadhav/Tkinter-Designer#185]
![Readme Banner](https://user-images.githubusercontent.com/48997634/152357554-25e23dc0-a095-4b36-ac1f-bf5061b4619b.png)

Hey Tkinter-Designer Community, I just finished updating the README for my project. Could you consider adding it to the examples for Tkinter Designer?

Repo Link: https://github.com/Just-Moh-it/HotinGo
Name: HotinGo - The coolest 🏖 Hotel Management System

The link to the Figma file is added in the README. Thanks

**Comment by ParthJadhav** [comment]
Hey @Just-Moh-it , That's great work ! I'll add it to the readme soon.

**Comment by AndresM77** [comment]
Just wanted to say that this is extremely impressive. Great work on that repo!

**Comment by ParthJadhav** [comment]
Added the Repo in the latest commit.
