### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by Mennaruuk** [ParthJadhav/Tkinter-Designer#187]
Dear Parth,

Hope life is treating you well.

If I use Figma Desktop, will the custom font I use there be carried over in Tkinter Designer?

Thank you.

**Comment by ParthJadhav** [comment]
The Fonts which are installed on your Machine would only be supported. If the Font you use in Figma Desktop it's probably installed on your Machine.

**Comment by Mennaruuk** [comment]
What about users who don't have that font on their PC? What will they see?

**Comment by ParthJadhav** [comment]
They will probably see a Fallback font. Like a default font - Arial or something.

**Comment by Mennaruuk** [comment]
Thank you. You are very smart.
