### ISSUE TITLE
Output doesn't look like Figma's

### ISSUE THREAD

**Issue by Mennaruuk** [ParthJadhav/Tkinter-Designer#188]
Good morning or evening Parth, I hope you are doing great.

I tried Tkinter Designer for the first time. Unfortunately, the output gui.py doesn't look much like my Figma project.

### Actual output
![image](https://user-images.githubusercontent.com/52135169/152926406-7049588d-e047-4072-87de-32cfa23a50d9.png)

### Expected output
![image](https://user-images.githubusercontent.com/52135169/152926648-2d075012-bc0b-4cee-a3ed-fe08089f919a.png)

Here is the link to my project:
`https://www.figma.com/file/KEk4cu9XKoWWgpsfp4PVoM/twayback-(Copy)?node-id=7%3A3`

Thank you for your help. I hope I am not bothering you, let me know if I am and I will shut up.

**Comment by ParthJadhav** [comment]
Hey, The fix is easy. Don't name the text anything which is related to elements. TextArea is for Multiline Entry. Just name ur text anything other than the element names. 

You can just change the name of text elements from being "TextArea" to "Text" and this will fix the issue.

**Comment by Mennaruuk** [comment]
Thank you for this. It works perfectly.

I think it'd be very helpful to add Text as one of the parameters in Docs.

Have a great day.

**Comment by ParthJadhav** [comment]
Yeah, Just did it. Good luck with your project !

**Comment by ParthJadhav** [comment]
Also you can have a look at :- 

https://github.com/Just-Moh-it/HotinGo

https://github.com/Just-Moh-it/HotinGo#6-installing-fonts

He explained about fonts in his readme. And included a font installation file. You can also checkout his repo, he did a great work. #185
