### ISSUE TITLE
Improvement for Release notes

### ISSUE THREAD

**Issue by piccoloser** [ParthJadhav/Tkinter-Designer#20]
## Disclaimer for Windows Users:
Windows Defender might prevent you from running Tkinter Designer when you first open the executable.

![windows_defender](https://user-images.githubusercontent.com/63938746/121048071-735cbc80-c784-11eb-821a-d735b31d88dc.jpg)

You can disregard this message. See [this thread on StackOverflow](https://stackoverflow.com/questions/44377666/pyinstaller-exe-throws-windows-defender-no-publisher) for more details. To run the program, click on **More info** > **Run anyway**.
If you have any concerns, you can always [run the program directly from the source code.](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/instructions.md#getting-started-2)

**Comment by piccoloser** [comment]
I don't think I'm able to edit the release notes myself, so I just put this here. Here's the copy/paste version:
```
## Disclaimer for Windows Users:
Windows Defender might prevent you from running Tkinter Designer when you first open the executable.

![windows_defender](https://user-images.githubusercontent.com/63938746/121048071-735cbc80-c784-11eb-821a-d735b31d88dc.jpg)

You can disregard this message. See [this thread on StackOverflow](https://stackoverflow.com/questions/44377666/pyinstaller-exe-throws-windows-defender-no-publisher) for more details. To run the program, click on **More info** > **Run anyway**.
If you have any concerns, you can always [run the program directly from the source code.](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/instructions.md#getting-started-2)
```

**Comment by ParthJadhav** [comment]
Thanks for the Help, Updated the readme.
