### ISSUE TITLE
Blank Screen without any elements

### ISSUE THREAD

**Issue by Devanshu-17** [ParthJadhav/Tkinter-Designer#204]
How to Fix ?

This issue happens due to Incorrect Naming

Try to fix it by reading the instruction carefully.

If the issue still persists, create an issue with the following details included.

1. Error Message "Element with the name: `IMAGE` cannot be parsed. Would be displayed as Black Rectangle"
2. Link to the Figma File : https://www.figma.com/file/AjmZ4gxs7JVXeIDaEu3vju/bg?node-id=0%3A1

I would be grateful for any help in this regard.

**Comment by AbdulkadirH5253** [comment]
@Devanshu-17 i might be able to help you out if I can a look at the figma file. I need access for it.
