### ISSUE TITLE
Can't find tkinter_designer.exe

### ISSUE THREAD

**Issue by LangChuanGYL** [ParthJadhav/Tkinter-Designer#209]
I am sorry to disturb you, I have just extracted the zip file and found that I cannot find the tkinter_designer.exe file, can you tell me how to fix it?
很抱歉打扰到你，我刚刚解压zip文件后发现找不到tkinter_designer.exe文件，能告诉我该如何解决吗？

**Comment by LangChuanGYL** [comment]
I browsed through and found that most tutorials execute python3 tkinter_designer.py but I couldn't find the tkinter_designer.py file either
我通过浏览发现大多数教程会执行python3 tkinter_designer.py 但是我也找不到tkinter_designer.py文件

**Comment by Laythe87** [comment]
Basically what I did is download the files on github and placed it in the user folder in my disk, then I manually executed the gui.py file, which opens the GUI and you can generate your file from there.

**Comment by AbdulkadirH5253** [comment]
hey @LangChuanGYL 
make sure you have python3 downloaded.
 
open your terminal or cmd and run these commands in order
git clone https://github.com/ParthJadhav/Tkinter-Designer.git
cd tkinter-designer
pip3 install -r requirements.txt
pip3 install tkdesigner
cd tkinter-designer (optional: only if u arent still in tkinter-designer directory after the pip3 steps)
cd gui
python3 gui.py

**Comment by ParthJadhav** [comment]
Thanks @AbdulkadirH5253 .
