### ISSUE TITLE
where is tkinter_designer.exe, I can not find it

### ISSUE THREAD

**Issue by sunjian-github** [ParthJadhav/Tkinter-Designer#219]
Hi everyone:
    I want install tkinter designer, but can not find **tkinter_designer.exe**
    refer to the docs, it should be Assets ,but int Assets ,it  not exists
    please help

**Comment by ParthJadhav** [comment]
Hey @sunjian-github Please refer to this guide -> https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md
