### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by ericdrosado** [ParthJadhav/Tkinter-Designer#222]
`Learn` repos should have a LEARN.md file to teach another student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn. 

If you feel your project is too large to teach step-by-step how to build it, consider just teaching a certain tool or implementation that your project utilizes.

**Comment by ParthJadhav** [comment]
@ericdrosado , Added learn.md.
