### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by ericdrosado** [ParthJadhav/Tkinter-Designer#224]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. I'm not familiar with Tkinter, so the current description doesn't resonate with me. If you would like to attract other users I would recommended updating your description a bit.  Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

**Comment by ParthJadhav** [comment]
Sorry for the delay... I came up with few different descriptions :-

- Drag and drop GUI creation for Python 
- Build Python GUI without code 
- An easy and fast way to create a Python GUI

Let me know which sounds more attractive @ericdrosado .

**Comment by ericdrosado** [comment]
Personally, I like `An easy and fast way to create a Python GUI`. Seeing "easy" and "fast" may appeal to other users.

**Comment by ParthJadhav** [comment]
Okay thanks ! Changed the description. Closing the issue.
