### ISSUE TITLE
Add additional templates

### ISSUE THREAD

**Issue by ericdrosado** [ParthJadhav/Tkinter-Designer#225]
I see you have two issue templates on your repo. As you know, issue templates are very helpful for a collaboration repo. 

We recommend creating a “Report Bug” and “Feature Request” issue template. 

Some suggested prompts/questions you can add to a “Report Bug” template are:

* Briefly describe the bug
* What is the expected behavior?
* Please provide step by step instructions on how to reproduce the bug

Some suggested prompts/questions you can add to a “Feature Request” issue template are:

* Briefly describe your feature request
* What problem is this feature trying to solve?
* How do we know when the feature is complete?

**Comment by ParthJadhav** [comment]
Hey @ericdrosado , I created a PR for this issue and pushed the changes.
