### ISSUE TITLE
all black screen

### ISSUE THREAD

**Issue by ryanbsdeveloper** [ParthJadhav/Tkinter-Designer#228]
I'm running from source code, apparently everything works. When I use "python gui.py" the tkinter window opens, but all black!
I use windows, and I installed all the requirements.txt libs globally on my machine.
link figma: https://www.figma.com/file/j3wZe6B6P2SnKkKhK40UH8/Untitled?node-id=0%3A1

**Comment by Nagsein** [comment]
I got the same result.

**Comment by Nagsein** [comment]
@ryanbsdeveloper, I have found the solution.

You have to change the names of your rectangles.
Every time you add a new rectangle in Figma it adds space and a number, then you have to remove it.

Check the correct names for each element:
https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#naming-is-important

Check your figma:
![image](https://user-images.githubusercontent.com/1562648/172067988-a0855f58-d455-44bf-9e87-188a512b03b1.png)

Check my test figma:
https://www.figma.com/file/3yGZVsaQoqEzmYUvrn6NMY/Untitled?node-id=0%3A1

**Comment by ParthJadhav** [comment]
@ryanbsdeveloper instructions to use this repo are here -> https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md

Thanks @Nagsein for help.
