### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by GirishKumarSharma** [ParthJadhav/Tkinter-Designer#232]
I have installed Python3 in my /usr/bin/python3 Version 3.10.4 on my Ubuntu 22.04 home PC.
I have successfully completed pip install tkdesigner and sudo apt install python3-poetry. I have also completed 3rd step i.e.
git clone https://github.com/ParthJadhav/Tkinter-Designer.git
cd tkinter-designer
pip install -r requirements.txt
without any error, but when I says poetry new myproj : 

`Traceback (most recent call last):`
`  File "/usr/bin/poetry", line 5, in <module>`
`    from poetry.console import main`
`  File "/usr/lib/python3/dist-packages/poetry/console/__init__.py", line 1, in <module>`
`    from .application import Application`
`  File "/usr/lib/python3/dist-packages/poetry/console/application.py", line 7, in <module>`
`    from .commands.about import AboutCommand`
`  File "/usr/lib/python3/dist-packages/poetry/console/commands/__init__.py", line 4, in <module>`
`    from .check import CheckCommand`
`  File "/usr/lib/python3/dist-packages/poetry/console/commands/check.py", line 2, in <module>`
`    from poetry.factory import Factory`
`  File "/usr/lib/python3/dist-packages/poetry/factory.py", line 18, in <module>`
`    from .repositories.pypi_repository import PyPiRepository`
`  File "/usr/lib/python3/dist-packages/poetry/repositories/pypi_repository.py", line 11, in <module>`
`    from cachecontrol import CacheControl`
`ModuleNotFoundError: No module named 'cachecontrol'`

I don't know, why I always get an error when I simply follows all the instructions of various github repo.

**Comment by JawadPy** [comment]
have you tried to install it?

**Comment by ParthJadhav** [comment]
Hey @GirishKumarSharma , May I know what are you trying to achieve ? You can simply run `tkdesigner `from command line if you have installed it from pip.

**Comment by GirishKumarSharma** [comment]
@ParthJadhav Thanks for your reply. I am just trying to run tkdesigner 
`girish@mypc:~/Tkinter-Designer/tkdesigner$ tkdesigner `
`usage: tkdesigner [-h] [-o OUTPUT] [-f] file_url token`
`tkdesigner: error: the following arguments are required: file_url, token`
`girish@mypc:~/Tkinter-Designer/tkdesigner$ ls`
`cli.py  conftest.py  constants.py  designer.py  figma  __init__.py  __pycache__  template.py  utils.py`
`girish@mypc:~/Tkinter-Designer/tkdesigner$ `

**Comment by GirishKumarSharma** [comment]
No problem, since its free and free things works like this way, I should close the issue. That's why there is and will no alternative of Microsoft's technologies which are paid and licensed. Closing the issue with frustration and sad.
