### ISSUE TITLE
How do I make my program go fullscreen and is tthere anything similar like relheight,rel width, relx, rely?

### ISSUE THREAD

**Issue by Ar998-max** [ParthJadhav/Tkinter-Designer#236]
It copies the dimensions of the figma project but I want it to resize itself accordingly to the size of the screen. And I am not able to find the things I listed above, so is there anything similar to do what I want?

**Comment by JawadPy** [comment]
the project doesn't support this future as I remember, you have to do it manually.

**Comment by HackingAllYT** [comment]
How would u do it manually?

**Comment by ernadosmic** [comment]
This worked for me.
```
window.attributes('-fullscreen', True)
```

**Comment by ParthJadhav** [comment]
Thanks @ernadosmic
