### ISSUE TITLE
Problems (spanish)

### ISSUE THREAD

**Issue by pbellob** [ParthJadhav/Tkinter-Designer#237]
Seguí paso a paso cada cosa, lo único diferente que fue diferente fue esto al momento de generar el tkdesinger     
"return f.write(data)
  File "C:\Users\paola\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 2400-2401: character maps to <undefined>"
 No me inicializa nunca la pantalla windows y cuando genero la carpeta no me aparece ningún código, me aparece vacío el código pero las "imagenes y botones" en  assets si aparece

**Comment by JawadPy** [comment]
share the line that cased this error so i can help you out

**Comment by HackingAllYT** [comment]
Mira el código que te genera y busca si se genera bien el texto que tienes, ya que las mayúsculas y otros caracteres similares no los trata bien.
