### ISSUE TITLE
Problems with 'tkinter_designer.py'

### ISSUE THREAD

**Issue by AlkisPis** [ParthJadhav/Tkinter-Designer#25]
I run 'tkinter_designer.py' and entered the following data:
Token ID: **111**
File URL: **https://github.com/ParthJadhav/Tkinter-Designer/**
Output path: **R:/w/x**

Problem 1:
If I enter the above path manually, I get "Invalid Output path" error. However, if I use the File selector the path is accepted, although and it is **exactly the same** with the one I set manually!!

Problem 2:
When I click on "Generate", I receive the error _"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"_
Here's the full traceback:
  File "G:\Python3\python-3.7.7\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "R:\W\x\backend.py", line 86, in generate_code
    data = response.json()
  File "G:\Python3\python-3.7.7\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "G:\Python3\python-3.7.7\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "G:\Python3\python-3.7.7\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "G:\Python3\python-3.7.7\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is this PY file published without being tested?

**Comment by ParthJadhav** [comment]
Thanks for creating an Issue, We will be eager to solve it.

**Comment by ParthJadhav** [comment]
Hello Alkis,

Thanks for trying the program. Sorry to say but you entered both things wrong. Please read the documentation correctly or watch this YouTube video -
https://youtu.be/mFjE2-rbpm8

Token is - Figma API token
URL is - the Url of the file you’ve designed before hand.

And for the file path you should choose a directory you have access to. Try choosing desktop.
