### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by roro627** [ParthJadhav/Tkinter-Designer#251]
hi ,
thank you for your work it's amazing but is it possible to add a rounded rectangle, this already exists for the button but not for the rectangle please add this

**Comment by ParthJadhav** [comment]
You can just name it 'Image' for now. I'll try to work on it .

**Comment by roro627** [comment]
> You can just name it 'Image' for now. I'll try to work on it .

thank you guy I did it manually but yes it must also work
