### ISSUE TITLE
What i want VS What i get

### ISSUE THREAD

**Issue by mohamed-29** [ParthJadhav/Tkinter-Designer#256]
![image](https://user-images.githubusercontent.com/63977915/190203871-7b7a74cc-b630-41c3-bf74-9fa00d50394c.png)

![image](https://user-images.githubusercontent.com/63977915/190203970-bc6533e3-fe3c-4097-ac04-b2afbe030e4c.png)

**Comment by ParthJadhav** [comment]
Name all images as 'Image' and check the YT tutorial, It's outdated but it will help u fix the white background around buttons

**Comment by ParthJadhav** [comment]
https://youtu.be/Qd-jJjduWeQ
