### ISSUE TITLE
Rounded TextBox and TextArea are not produced as expected

### ISSUE THREAD

**Issue by Leoxhiu** [ParthJadhav/Tkinter-Designer#258]
Rounded buttons work fine with the steps provided, but it is not as expected when comes to rounded text box and text area.
Not sure if I did anything wrong.

### Expected:
![image](https://user-images.githubusercontent.com/91444493/193097424-c2f183ea-0e82-4201-aed6-193e95b0bc1b.png)
![image](https://user-images.githubusercontent.com/91444493/193105718-69115db7-a99f-4574-815d-ad383f5b09ae.png)

### Outcome:
![image](https://user-images.githubusercontent.com/91444493/193097623-548385a4-3470-43c0-84bb-5078136f0087.png)
![image](https://user-images.githubusercontent.com/91444493/193105784-1aef655d-aa0f-4d02-88d8-ca5af64be784.png)

### Figma:
I have followed the documentation and YouTube tutorial to group and name the elements.
![image](https://user-images.githubusercontent.com/91444493/193098005-7b1778a7-a3de-4c06-8326-37aa503491af.png)
![image](https://user-images.githubusercontent.com/91444493/193103883-51208f7a-434c-4245-b744-c4619a820444.png)

### Generated code:

> TextBox

```
img_email_entry = PhotoImage(
    file=relative_to_assets("entry_1.png"))
email_entry_bg = canvas.create_image(
    240.0,
    149.0,
    image=img_email_entry
)
email_entry = Entry(
    bd=1,
    bg="#FFFFFF",
    highlightthickness=0
)
email_entry.place(
    x=135.0,
    y=134.0,
    width=210.0,
    height=28.0
)
```

> TextArea

```
entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    593.0,
    290.0,
    image=entry_image_5
)
entry_5 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
entry_5.place(
    x=440.0,
    y=188.0,
    width=306.0,
    height=202.0
)
```

**Comment by ParthJadhav** [comment]
Hey @Leoxhiu , I guess there was a section in the Youtube video where I say that we don't need to group the elements for textbox & text area.

**Comment by ParthJadhav** [comment]
Just use a normal rectangle for text box rather than a group..

Closing this @Leoxhiu
