### ISSUE TITLE
Exception in Tkinter callback: KeyError: 'color'

### ISSUE THREAD

**Issue by persistence0x1** [ParthJadhav/Tkinter-Designer#26]
Basically if I run the script I get this error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Kyle\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\Kyle\Documents\Equinox\Tkinter-Designer-master\tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\Users\Kyle\Documents\Equinox\Tkinter-Designer-master\backend.py", line 152, in generate_code
    element_color = get_color(element)
  File "C:\Users\Kyle\Documents\Equinox\Tkinter-Designer-master\backend.py", line 9, in get_color
    el_r = element["fills"][0]["color"]['r'] * 255
KeyError: 'color'`

It is however able to retrieve all TextBox and Button elements from the Figma page before prompting this error.

**Comment by ParthJadhav** [comment]
Thanks for creating an Issue, We will be eager to solve it.

**Comment by persistence0x1** [comment]
It is however able to retrieve all TextBox and Button elements from the Figma page before prompting this error.

**Comment by ParthJadhav** [comment]
Can you share the link to the Figma document?

**Comment by persistence0x1** [comment]
> Can you share the link to the Figma document?

[Here](https://www.figma.com/community/file/986683294609856375/Equinox-UI) you go.

**Comment by ParthJadhav** [comment]
Thanks, let me see.

**Comment by ParthJadhav** [comment]
Hey, Saw the file. There are multiple things which are incorrect. 

1. Text should not be named TextArea. TextArea is for multiline input.

2. Buttons should have a rectangle as a background matching to the background colour.

3. Strokes and drop shadows are not supported. All such effects btw.

4. Rectangle should be pure rectangles. You used image as a rectangle.

5. The frame should be on 0,0 coordinates.

Please check the video or instructions. 

Fixed the issues in this [version](https://www.figma.com/community/file/986690136254143353/Equinox-UI-(Community)-Fixed), tweak it as per your liking. 


![image](https://user-images.githubusercontent.com/42001064/122100665-0951b080-ce31-11eb-89da-281e1ed40fa8.png)


Let me know if you need any more help.

**Comment by persistence0x1** [comment]
Worked great! Thank you so much.

**Comment by ParthJadhav** [comment]
Nice to hear that ✌️
