### ISSUE TITLE
where is tkinter_designer.exe?

### ISSUE THREAD

**Issue by KKBIRD23** [ParthJadhav/Tkinter-Designer#260]
where is tkinter_designer.exe?This file was not found

**Comment by wusuhuang** [comment]
+1

**Comment by kroomz** [comment]
Its missing.
You can start the application by navigating to the folder where "gui.py" is
"C:\yourpath\Tkinter-Designer-master\Tkinter-Designer-master\gui\gui.py"
in your Terminal just do "py gui.py"

**Comment by ParthJadhav** [comment]
Thanks @kroomz !
