### ISSUE TITLE
Can it support multi frames?

### ISSUE THREAD

**Issue by Reed-roll** [ParthJadhav/Tkinter-Designer#268]
I'm making a project that requires you to switch frames with each button click, does this not support that? 

I tried it and it worked, but only displayed the last page(frame) which I didn't want.

**Comment by ParthJadhav** [comment]
Hey @Reed-roll , I've created a Pull request which lets you do that

**Comment by ParthJadhav** [comment]
@Reed-roll , Multi-Frame support is added. Clone the latest version and try again.
