### ISSUE TITLE
Blank interface

### ISSUE THREAD

**Issue by misska1** [ParthJadhav/Tkinter-Designer#27]
I tested a simple project in figma,but I got a blank Tkinter interface using tkinter designer
<img width="410" alt="截屏2021-06-16 上午11 28 35" src="https://user-images.githubusercontent.com/22286006/122153655-ffae6400-ce95-11eb-9ccc-f1d25938f78d.png">

**Comment by ParthJadhav** [comment]
Thanks for creating an Issue, We will be eager to solve it.

**Comment by ParthJadhav** [comment]
Can I see the Figma file ?

**Comment by misska1** [comment]
<img width="432" alt="截屏2021-06-16 上午11 31 11" src="https://user-images.githubusercontent.com/22286006/122153844-5e73dd80-ce96-11eb-91f4-8c4f20e02fe4.png">

**Comment by ParthJadhav** [comment]
Click in the frame and check the coordinates of it...

**Comment by ParthJadhav** [comment]
Make sure they are -

X - 0
Y - 0

**Comment by misska1** [comment]
<img width="198" alt="截屏2021-06-16 上午11 33 38" src="https://user-images.githubusercontent.com/22286006/122154036-b4e11c00-ce96-11eb-85c5-3abdaf1a5b09.png">
they are

**Comment by ParthJadhav** [comment]
Can I see the naming of the elements?

**Comment by misska1** [comment]
<img width="224" alt="截屏2021-06-16 上午11 35 11" src="https://user-images.githubusercontent.com/22286006/122154155-eb1e9b80-ce96-11eb-8383-5b60918c8234.png">

**Comment by ParthJadhav** [comment]
Oh, you need to name it according to the instructions.

Change the names to -

Text -> No change needed
Rectangle 2 -> Rectangle
Rectangle - -> Rectangle

**Comment by misska1** [comment]
ok!!!! thank you~

**Comment by misska1** [comment]
nice work for u!

**Comment by ParthJadhav** [comment]
Great! Do the same for all the elements- 

Buttons -> Button
Rectangle -> Rectangle 
Entry -> TextBox
TextArea -> TextArea
Background -> Background 
Text -> No Need to name

**Comment by ParthJadhav** [comment]
Closing the issue, reopen for any more help.
