### ISSUE TITLE
AttributeError: module 'tkinter' has no attribute 'messagebox'

### ISSUE THREAD

**Issue by AlwaysPP** [ParthJadhav/Tkinter-Designer#286]
AttributeError: module 'tkinter' has no attribute 'messagebox'

**Comment by fbrh67** [comment]
Hey, I have the same issue.

My Error Message is:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/pi/Tkinter-Designer/gui/gui.py", line 63, in btn_clicked
    response = tk.messagebox.askyesno(
AttributeError: module 'tkinter' has no attribute 'messagebox'

**Comment by KuriYama-mirai524** [comment]
me too

File "c:/Users/Daisy/Documents/Tkinter-Designer-1.0.5/Tkinter-Designer-1.0.5/gui/gui.py", line 63, in btn_clicked
    response = tk.messagebox.askyesno(
AttributeError: module 'tkinter' has no attribute 'messagebox'

**Comment by KuriYama-mirai524** [comment]
I think I found a way
Delete the assignment of line 63 and change it to any text
![image](https://user-images.githubusercontent.com/93362741/204465661-18b645aa-a2a8-4f0a-912f-0672f7b84884.png)
![image](https://user-images.githubusercontent.com/93362741/204465698-50db730b-dc0d-45fe-bca3-30718072c144.png)
