### ISSUE TITLE
Tkinter-Designer doesn't export my design exacly!

### ISSUE THREAD

**Issue by CJSparrow** [ParthJadhav/Tkinter-Designer#30]
let me make it shorter, check the picture below

![image](https://user-images.githubusercontent.com/65213455/122240391-69e0fc00-ceca-11eb-9401-8829e168ee1e.png)

this is my naming for all elements:
![image](https://user-images.githubusercontent.com/65213455/122240601-9268f600-ceca-11eb-8f50-cfbfbb9700db.png)

what's wrong?

**Comment by ParthJadhav** [comment]
Thanks for creating an Issue, We will be eager to solve it.

**Comment by CJSparrow** [comment]
> 
> 
> Thanks for creating an Issue, We will be eager to solve it.

do you want the link of the design in private so it might help you out?

**Comment by ParthJadhav** [comment]
Yes, I'll need the design link. You can share it here too. But if you want to keep it private-

Send it here - jadhavparth99@gmail.com

**Comment by ParthJadhav** [comment]
But as I see, I found some issues-

- Tkinter designer dose not support rounded rectangles.
- Nor the image on the left. You need to add it manually.
- The font you used for the message text should be installed on your computer. Try using a generic font like Arial
-  The Buttons should have a background in their group. Steps to create a button-

> 1. Create the button using rectangle 
2. Add the text.
3. Add a background- just a rectangle touching the sides behind the button. And make it same colour as background.
4. Select all four and press ctrl + G and name it Button.

- You can add all unsupported elements like the rounded rectangles to the Background group. So it would be created as image. To do this - select all the unsupported elements and press ctrl + g and name the group _Background_ .
- Windows OS increases the font size of the texts. You need to reduce it manually.

Here are some examples - 
Click on duplicate after opening the link.

https://www.figma.com/community/file/986977867287037912

https://www.figma.com/community/file/986991626144349151


Let me know if you need help.

**Comment by CJSparrow** [comment]
I'll follow your comment, and I sent you the design link.
remove ur email to avoid spammers on web if you feel it's right.

**Comment by ParthJadhav** [comment]
Yes, I saw it but I can only view it. But anyways did the instructions solved the problem?

**Comment by CJSparrow** [comment]
> 
> 
> Yes, I saw it but I can only view it. But anyways did the instructions solved the problem?

nope :(, i'll give you editing promotions..

**Comment by ParthJadhav** [comment]
What's the issue now ? Is it the same?

**Comment by CJSparrow** [comment]
> 
> 
> What's the issue now ? Is it the same?

the image and font aren't my problem, actually the rectangle and buttons doesn't show as it should, that's my issue. 
also idk how to put bg color for a rounded button/rectangle  to fit it. Ik that tkinter doesn't support jpg images, but it can support png, and the buttons are png! it confusing me. did you use another method than `Text(image=...)` for displaying images in tkinter?

**Comment by ParthJadhav** [comment]
Nope, I am using the image as a background but tkinter puts this grey thing around the png if it's transparent. To takle that we add a background to the button group which makes it a untransparent png. I'll edit the file, no worries ✌️

**Comment by CJSparrow** [comment]
> 
> 
> > What's the issue now ? Is it the same?
> 
> the image and font aren't my problem, actually the rectangle and buttons doesn't show as it should, that's my issue.
> also idk how to put bg color for a rounded button/rectangle to fill it. Ik that tkinter doesn't support jpg images, but it can support png, and the buttons generated in png! it confusing me. did you use another method than `Text(image=...)` for displaying images in tkinter?

as far as I checked the code, you used `canvas.create_image` to display images. using `Label(image=...)` works fine

**Comment by CJSparrow** [comment]
> 
> 
> Nope, I am using the image as a background but tkinter puts this grey thing around the png if it's transparent. To takle that we add a background to the button group which makes it a untransparent png. I'll edit the file, no worries ✌️

u r right, i'll try to find a solution for that too

**Comment by ParthJadhav** [comment]
Yes, Look at the examples I sent. you'll get the idea behind the process.
