### ISSUE TITLE
The text placement

### ISSUE THREAD

**Issue by Uduno** [ParthJadhav/Tkinter-Designer#315]
As you can  see the text don't really fit in the blue area:
![image](https://user-images.githubusercontent.com/100622850/220906004-a21e3fb0-0612-488d-abca-d94c33df9238.png)

My classmate and I fixed it like that:
![image](https://user-images.githubusercontent.com/100622850/220906569-eca43bcc-83bb-4e61-8f8b-3152ecc591a0.png)
pull resquest #314

**Comment by Pifton** [comment]
We have to precise that it happens on Linux OS, we both use gnome as our desktop environment in case it matters

**Comment by Uduno** [comment]
@ParthJadhav can you accept our pull request? That's our first contribution (sorry for my poor english)

**Comment by ParthJadhav** [comment]
Hey @Uduno @Pifton , Thanks for the contribution. Can you also change the `x` of all the elements on the left side so that they align perfectly?

**Comment by Uduno** [comment]
yes we gonna do it

**Comment by Uduno** [comment]
@ParthJadhav it's done
