### ISSUE TITLE
Request for Chinese Translation

### ISSUE THREAD

**Issue by 01men** [ParthJadhav/Tkinter-Designer#32]

**Comment by ParthJadhav** [comment]
Thanks for creating an Issue, We will be eager to solve it.

**Comment by ParthJadhav** [comment]
Please provide description about the issue.

**Comment by 2926295173** [comment]
Let me help him write a description. Your project is very good. It has attracted a large number of Chinese code lovers to learn. However, due to language differences, it is too difficult to learn. Could you please give us a Chinese version?

**Comment by ParthJadhav** [comment]
Hey @2926295173 , I didn't knew that. Thanks for telling me. But I don't know Chinese... 
Would you do that for me ? I could use google translate but I would not know if there are any mistakes in translation.

**Comment by 2926295173** [comment]
please use Google translate first. Then I will help you.

**Comment by ParthJadhav** [comment]
Yup, That would work. I'll start the translation soon...

**Comment by 2926295173** [comment]
ok.

**Comment by 2926295173** [comment]
please change the title"求大神来个汉化版的" to English

**Comment by ParthJadhav** [comment]
Oh I didn't see the title translation...

Is this what it mean?-

Seeking the whole Chinese version of the Great God

**Comment by 01men** [comment]
yes!



---原始邮件---
发件人: "Parth ***@***.***&gt;
发送时间: 2021年6月17日(周四) 下午4:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ParthJadhav/Tkinter-Designer] 求大神整个汉化版的 (#32)




 
Oh I didn't see the title translation...
 
Is this what it mean?-
 
Seeking the whole Chinese version of the Great God

**Comment by ParthJadhav** [comment]
Oh Wow ! Chinese is cool.

**Comment by ParthJadhav** [comment]
@2926295173  Can you tell me which Chinese to translate to ? I am confused... There is simplified Chinese and other things...

**Comment by 2926295173** [comment]
Hey, simplified Chinese is the first choice（zh-CN）. Just like its name, it looks relatively simple. It's also an official language. More people use it. 
But Traditional Chinese is ancient (less people use it)

**Comment by ParthJadhav** [comment]
Oh Got it ! I'll start the translation.

**Comment by 01men** [comment]
您好，简体中文(Hello, simplified Chinese)

---Original---
From: "Parth ***@***.***&gt;
Date: Thu, Jun 17, 2021 22:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ParthJadhav/Tkinter-Designer] Request for Chinese Translation (#32)




 
@2926295173  Can you tell me which Chinese to translate to ? I am confused... There is simplified Chinese and other things...

**Comment by 01men** [comment]
辛苦了，来自中国用户的感谢！(Thanks from Chinese users!)



---Original---
From: "Parth ***@***.***&gt;
Date: Thu, Jun 17, 2021 23:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ParthJadhav/Tkinter-Designer] Request for Chinese Translation (#32)




 
Oh Got it ! I'll start the translation.

**Comment by ParthJadhav** [comment]
我的荣幸！

**Comment by 01men** [comment]
👍👍👍



---Original---
From: "Parth ***@***.***&gt;
Date: Thu, Jun 17, 2021 23:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ParthJadhav/Tkinter-Designer] Request for Chinese Translation (#32)




 
我的荣幸！

**Comment by ParthJadhav** [comment]
Hey @01men , @2926295173  我已经添加了中文自述文件，请验证它们，如果有任何更改，请告诉我。 您也可以创建更改的拉取请求。

**Comment by 2926295173** [comment]
ok.

**Comment by ParthJadhav** [comment]
Is it correct @2926295173 ?

**Comment by ParthJadhav** [comment]
I guess it's correct after the pull request from @2926295173 . Closing the issue.
