### ISSUE TITLE
Convert codebase to use customtkinter

### ISSUE THREAD

**Issue by dishb** [ParthJadhav/Tkinter-Designer#335]
### Briefly describe your feature request
`customtkinter` is so much better than normal `tkinter` (or even `tkinter.ttk`) that it is impossible to describe. Much more user friendly, an amazingly well documented API, modern GUI, a big community on Github, the project is open-source, and CTk has a growing ecosystem of extensions!
### What problem is this feature trying to solve?
It would make the applications generated by this (quite revolutionary and useful) tool look a lot better.
### How do we know when the feature is complete?
When all instances/mentions of `tkinter` are replaced with `customtkinter`. Granted, CTk doesn't have a few things that Tk does such as the `Menu` widget in Tk. So I should rephrase to everything that _can_ be replaced _should_ be replaced.
### Is there any possible approach you have thought of? If yes then how?
I believe it'll have to be manual. `Cmd+F` (or `Ctrl+F` for you inferior Windows users) should help in the process.
### Would you like to participate in development of this feature?
Of course! I am fanboy over `customtkinter` the way many stan for Dream or fanboy/fangirl over K-Pop. I've created one application with CTk but, thanks to the documentation, I feel ready to take on this issue. I do hope other people would work with me on this issue as it is transforming the code base of the entire project (and affects core functionality).

_The above stuff were mainly jokes, I'm not actually hating on anyone for using Windows! (or liking K-Pop)_

**Comment by dishb** [comment]
I'll begin work on my own fork. Even if this issue/feature is not accepted, I'll have my own fork with CTk support.

**Comment by ParthJadhav** [comment]
Hey @dishb , The whole point of this project is to:
1. Avoid extra dependencies as `tkinter` is built-in module for python.
2. Allow extensive customisation through use of Figma.

Granted `custom-tkinter` looks amazing out of the box, but that wouldn't help Tkinter-Designer because all the designs for Tkinter-Design comes from Figma which you can customise according to your will.

**Comment by ParthJadhav** [comment]
Thank you for considering to work on this project, You can pick up any other issue if you want to contribute to this project 😄

**Comment by dishb** [comment]
Gotcha, thanks for the explanation! :)
