### ISSUE TITLE
Get  Error X , Y

### ISSUE THREAD

**Issue by CL545740896** [ParthJadhav/Tkinter-Designer#34]
[{'id': '2:2', 'name': 'Hello World', 'type': 'TEXT', 'blendMode': 'PASS_THROUGH', 'absoluteBoundingBox': {'x': 493.0, 'y': -37.0, 'width': 200.0, 'height': 44.0}, 'preserveRatio': True, 'constraints': {'vertical': 'TOP', 'horizontal': 'LEFT'}, 'fills': [{'blendMode': 'NORMAL', 'type': 'SOLID', 'color': {'r': 0.8980392217636108, 'g': 0.8980392217636108, 'b': 0.8980392217636108, 'a': 1.0}}], 'strokes': [], 'strokeWeight': 1.0, 'strokeAlign': 'OUTSIDE', 'effects': [], 'characters': 'Hello World\n', 'style': {'fontFamily': 'Arial', 'fontPostScriptName': 'ArialMT', 'fontWeight': 400, 'fontSize': 30.0, 'textAlignHorizontal': 'CENTER', 'textAlignVertical': 'TOP', 'letterSpacing': 0.0, 'lineHeightPx': 35.15625, 'lineHeightPercent': 100.0, 'lineHeightUnit': 'INTRINSIC_%'}, 'characterStyleOverrides': [], 'styleOverrideTable': {}}]

note:
 right:
     x: 209
     y: 138

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Can you elaborate little more?

**Comment by CL545740896** [comment]
> Can you elaborate little more?

https://www.figma.com/file/nXuJopbavmgOKXnoHm07b9/Untitled?node-id=0%3A1

**Comment by CL545740896** [comment]
![image](https://user-images.githubusercontent.com/27679586/122532261-eb639600-d052-11eb-88fa-84acbacb1dfc.png)

**Comment by ParthJadhav** [comment]
让我看看

**Comment by ParthJadhav** [comment]
你能给我编辑权限吗？

**Comment by CL545740896** [comment]
> 你能给我编辑权限吗？

可以

**Comment by ParthJadhav** [comment]
如果它不起作用，我有一个解决方案。 将框架的 X 和 Y 坐标更改为 0.

![Screenshot 2021-06-18 at 2 09 16 PM](https://user-images.githubusercontent.com/42001064/122533412-2a87ec00-d03f-11eb-9018-6061931ab58a.png)

见右侧

**Comment by CL545740896** [comment]
可以 ！
