### ISSUE TITLE
Frame not found in figma file or is empty

### ISSUE THREAD

**Issue by JamalTyroe** [ParthJadhav/Tkinter-Designer#347]
I cant generate because of the frame error even tho i actually have a frame.
![Screenshot 2023-08-27 104213](https://github.com/ParthJadhav/Tkinter-Designer/assets/143315127/db8bc46b-898d-4efa-8256-b0030cf22152)

**Comment by HammadRafique29** [comment]
Tell me more about the problem, what are you trying to dooo

**Comment by vincentperezzz** [comment]
I do get the same issue, is there anyone still making an update to this repo?

**Comment by josh-trumed** [comment]
I'm having this issue too :(

**Comment by barandenizdogan** [comment]
Read the Install Instructions carefully. You should do following steps.
1- pip install tkdesigner
Thats gonna fix all the problems. Clonnig repo and installing requirements not enough.

**Comment by josh-trumed** [comment]
Hi,

I did read the instructions carefully and followed every step. There seems to be an issue with Pillow upon installation, maybe this could be contributing to the problem?

***@***.***

Best,
Josh

**Comment by barandenizdogan** [comment]
Hi,

Which Python version do you use?


josh-trumed ***@***.***>, 7 Kas 2023 Sal, 22:37 tarihinde
şunu yazdı:

**Comment by josh-trumed** [comment]
Python 3.12

**Comment by barandenizdogan** [comment]
Try to change with 3.11

8 Kas 2023 Çar, saat 02:10 tarihinde josh-trumed ***@***.***>
şunu yazdı:

**Comment by josh-trumed** [comment]
Just tried with 3.11 and got the same error when running pip install tkdesigner.

**Comment by josh-trumed** [comment]
***@***.***

From: Josh Kay
Sent: Wednesday, November 8, 2023 8:35 AM
To: ParthJadhav/Tkinter-Designer ***@***.***>; ParthJadhav/Tkinter-Designer ***@***.***>
Cc: Comment ***@***.***>
Subject: RE: [ParthJadhav/Tkinter-Designer] Frame not found in figma file or is empty (Issue #347)

Just tried with 3.11 and got the same error when running pip install tkdesigner.

**Comment by barandenizdogan** [comment]
Did you recieved the error while pip install?

8 Kas 2023 Çar, saat 19:35 tarihinde josh-trumed ***@***.***>
şunu yazdı:

**Comment by josh-trumed** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by barandenizdogan** [comment]
Can you try to install certifi, chardet, idna, jinja2, markupsafe, pillow,
requests, urllib3.
Basicly written on the requirements.txt and then try to install tkdesigner.

9 Kas 2023 Per, saat 08:04 tarihinde josh-trumed ***@***.***>
şunu yazdı:

**Comment by josh-trumed** [comment]
Did all of the requested steps and still got the same error “Failed building wheel for Pillow”.

**Comment by barandenizdogan** [comment]
Thats another error. I think as a frame error. Can you try sudo permission
to install?

9 Kas 2023 Per, saat 21:28 tarihinde josh-trumed ***@***.***>
şunu yazdı:

**Comment by josh-trumed** [comment]
I ran cmd as an administrator then ran py -m pip install tkdesigner…still nothing. The no frame error I was getting was when I used the gui.py instead of command line.

**Comment by barandenizdogan** [comment]
Can you try to update setuptools with ‘Python -m pip install —update
setuptools wheel’. I was getting that error and fixed that. I am trying to
remember the solution.

9 Kas 2023 Per, saat 21:37 tarihinde josh-trumed ***@***.***>
şunu yazdı:

**Comment by josh-trumed** [comment]
Getting the following error now:

***@***.***

**Comment by barandenizdogan** [comment]
I cannot properly see that. Can you reach me via Telegram?
@barandenizdogan

9 Kas 2023 Per, saat 21:46 tarihinde josh-trumed ***@***.***>
şunu yazdı:

**Comment by DetroNot74** [comment]
1.Should contain a frame.
2.Every element of your project should be NESTED _inside_ the FRAME.
i had my elements outside the frame.fixed by nesting inside the frame
