### ISSUE TITLE
Elements not visible.

### ISSUE THREAD

**Issue by 13Abhishek** [ParthJadhav/Tkinter-Designer#35]
Hey after giving token and url and generating file.The file generated is always 1kb and and just shows a blank window of the same size I want to import without any inner object and its code.

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Can you share the figma link?

**Comment by 13Abhishek** [comment]
Yeshttps://www.figma.com/file/k4PigyWo8SF29ehKBlEq8m/Material-Design-Desktop-Kit-for-Figma-Free-Edition-Copy?node-id=126%3A1017 Sent from Mail for Windows 10 From: Parth JadhavSent: Friday, June 18, 2021 5:05 PMTo: ParthJadhav/Tkinter-DesignerCc: 13Abhishek; AuthorSubject: Re: [ParthJadhav/Tkinter-Designer] Hey after giving token and url and generating file.The file generated is always 1kb and and just shows a blank window of the same size I want to import without any inner object and its code (#35) Can you share the figma link?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ParthJadhav** [comment]
Hey @13Abhishek, you are using a pre created UI kit which is not configured for Tkinter Designer.

I'll suggest you to create a new file and add elements to it one by one by seeing following instructions and watching the YouTube video for more information.

**Comment by 13Abhishek** [comment]
85300 81736  can you contact here WA

**Comment by 13Abhishek** [comment]
https://www.figma.com/file/GXmYjaMwsKsGxducK68rlO/Untitled

**Comment by ParthJadhav** [comment]
Sorry @13Abhishek, I can't contact you. Please ask your queries here. 

You can see this example - 
https://www.figma.com/file/x7uIyv3e7io4JolHiDhI5p/Example?node-id=0%3A1

Try using this link and see how the elements are named and placed.

https://www.figma.com/file/x7uIyv3e7io4JolHiDhI5p/Example?node-id=0%3A1

**Comment by ParthJadhav** [comment]
> https://www.figma.com/file/GXmYjaMwsKsGxducK68rlO/Untitled

Also, this link is not working...
