### ISSUE TITLE
Cannot have buttons open other windows

### ISSUE THREAD

**Issue by brianmanderson** [ParthJadhav/Tkinter-Designer#36]
Hello,

I've been having an issue with creating GUI's which navigate to other frames. I've tried centering both frames on X=0, Y=0, but only the primary frame is created.

Is this currently supported?

Thank you!
Brian

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
No @brianmanderson, Currently multiple frames are not supported. You need to manually create them. 

Only the first frame in the layers panels is converted. If you want you can change the order of frames and get them converted separately. And then you can choose a different output path for all. And at last combine all of them and then add the functions.

We would be adding this feature in the next version.

Hope that helps!

**Comment by ParthJadhav** [comment]
Can I close this issue @brianmanderson, Or do you have any other questions. I'll be eager to help.
