### ISSUE TITLE
Can matplotlib figure add with designer?

### ISSUE THREAD

**Issue by xichaoqiang** [ParthJadhav/Tkinter-Designer#4]
Can matplotlib figure add with designer?

**Comment by ParthJadhav** [comment]
Not directly.

you can either use a static image as a for matpolib figure and include it in background.

or

you can design the remaining interface using Tkinter Designer and leave empty space for it and add matpolib designer manualy.

**Comment by xichaoqiang** [comment]
Thanks

**Comment by ParthJadhav** [comment]
Reopen this issue if you need any help ✌️
