### ISSUE TITLE
Problem with URL

### ISSUE THREAD

**Issue by Gabrielgsoares** [ParthJadhav/Tkinter-Designer#404]
Hello! I would like some help because I'm having problems generating the code in Tkinter Designer, when I press the "Generate" button the message appears: "Please enter a valid file URL." Even though I put the right figma link
![Captura de Tela 2024-05-09 às 11 18 43](https://github.com/ParthJadhav/Tkinter-Designer/assets/77746344/d17ed5bf-92c8-4557-9ef6-5717f8433b72)

**Comment by Youssef18118** [comment]
Same problem

**Comment by Developer-from-italy** [comment]
me too, let me know if you find a solution

**Comment by Raatexx** [comment]
same thing, i don't found the problem

**Comment by MvrPgi** [comment]
same issue
![image](https://github.com/ParthJadhav/Tkinter-Designer/assets/122778238/1ca53c18-68c1-43a4-ade4-dd184b4a2393)

**Comment by Andreanbudi** [comment]
If your URL is : https://www.figma.com/design/XX/YY
Change "design" with "file", so it will be : https://www.figma.com/file/XX/YY

**Comment by MvrPgi** [comment]
it worked.. thank you so much

**Comment by ParthJadhav** [comment]
solved in latest commit.
