### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by extio1** [ParthJadhav/Tkinter-Designer#408]
As I found figma changed url template for design files.
https://forum.figma.com/t/any-update-figma-to-url-structure/72061

So. When launching designer for new URL there is the error "Please enter a valid file URL."
Probable solution is to change regexp for url matching just before (gui.py:48)

- Operating System
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian

- What is the expected behavior?
no error

- Please provide step by step instructions on how to reproduce the bug
use Tkinter-Designer gui.py as usually

**Comment by ParthJadhav** [comment]
solved in latest commit.
