### ISSUE TITLE
No button in Figma Design  

### ISSUE THREAD

**Issue by AlkisPis** [ParthJadhav/Tkinter-Designer#41]
In **"How to use Tkinter Designer"** in https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md, _"Formatting Your Figma Design"_ -> 2. _Element Guide_ -> 7. _Button_:  It talks about the creation of a button but not how. In fact, and ironically enough, this is the only thing that I needed an explanation for! :) I can't find anything about buttons ...

**Comment by ParthJadhav** [comment]
I see, let me add some more information on it.

Sorry for inconvenience.

**Comment by ParthJadhav** [comment]
Hey @AlkisPis , 

Can you check the updated instructions. They more informative now.

**Comment by AlkisPis** [comment]
Hi

But I just did that. I was redirected to https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md. Are there other instructions available elsewhere?

Alkis Piskas


Sent from Mail for Windows 10

**Comment by ParthJadhav** [comment]
There is a youtube video available. I added the link to that video with timestamp in the instructions. 
[Check the updated elements guide.](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#2-element-guide)

**Comment by AlkisPis** [comment]
Thanks. I checked the updated guide. I didn’t see any apparent difference. As for the “button” section. It still doesn’t tell how to do it. I wonder why’s that so difficult. 

Now, about the video.  I don’t lke videos so much as a means for instructions. They are too slow as a communication form. Anyway I checked it and I had permently a large strip across the part explaining the creation of the button (quite complicated, indeed!). What’s that strip and why should it be there? It makes watching unbearable!




Parth, I am sorry I have to bring up all that. I could well avoid all that altogether and say nothing. But you have done a very good job on this, and also Figma is just great! So, I believe it would be pity to just forget about the whole Tkinter Designer. Wouldn’t it be?

Alkis

Sent from Mail for Windows 10

**Comment by ParthJadhav** [comment]
Yes, I agree about the tutorial. I am going to make a new and better tutorial.

But before that I am consistently working on the experimental branch to make it more easier to work with. The naming system would be completely replaced with a plug-in. It would allow you select the type of element it is. The text if the buttons would be now dynamic unlike now which is a image. Also I am working on removing the background for button process.

So overall there would be a lot of changes and improvements in Tkinter Designer in upcoming version.

Also it's important to point out things which are not good. So any critics are welcome 😃

**Comment by AlkisPis** [comment]
Thanks about all that and esp. your willingness, eagerness I would say,  to make improvements. It is a sign of a wise and intelligent person! 

As for the critic, I wouldn’t put my comments into that category. I would rather put them under feedback from beta testing! Besides, we are programmers, aren’t we? 😀 (And I have done really a lo-o-o-o-t of beta testing in my life!)

BTW, have you checked the generated code I sent you?

Cheers


Sent from Mail for Windows 10

**Comment by ParthJadhav** [comment]
> Thanks about all that and esp. your willingness, eagerness I would say, to make improvements. It is a sign of a wise and intelligent person! As for the critic, I wouldn’t put my comments into that category. I would rather put them under feedback from beta testing! Besides, we are programmers, aren’t we? 😀 (And I have done really a lo-o-o-o-t of beta testing in my life!) 

Nice to hear that! As we already talked, If you love it then you'll spend your life fixing it. 

Oh, I See. You must have good experience of beta testing. Can I ask you to test the experimental branch once it's ready ?

**Comment by AlkisPis** [comment]
Hi

Re “test the experimental branch once it's ready”:  Of course

Alkis

**Comment by ParthJadhav** [comment]
Thanks a lot @AlkisPis.
