### ISSUE TITLE
"Invalid URL!" Error

### ISSUE THREAD

**Issue by AngeleAkane** [ParthJadhav/Tkinter-Designer#411]
I have been using Tkinter Designer very quietly but recently this tool started giving the error "Invalid URL! - Please, enter a valid file URL", but obviously I have already done this procedure several times and now doesn't work. In none of the windows I have developed.

I thought it was the URL, it is not (I do the same procedure as before and changed the access type through the URL). I thought it was the Token, it is not (I've created another).

I assume Figma has changed something, probably in the URL format. No idea.

By the way, thanks for creating this tool!

Edit: I also thought it was something of my own, but it seems I'm not the only one.

**Comment by AngeleAkane** [comment]
I also thought it was something of my own, but it seems I'm not the only one.

**Comment by anuragverma77** [comment]
I've mentioned a solution here.
https://github.com/ParthJadhav/Tkinter-Designer/issues/412

**Comment by AngeleAkane** [comment]
> I've mentioned a solution here. #412

Yeah, thanks. Anyway I will CopyPaste here:

**go to gui/gui.py and replace at line https://github.com/ParthJadhav/Tkinter-Designer/issues/48
`r'https://www.figma.com/file/([0-9A-Za-z]+)', URL.strip())`
with
`r'https://www.figma.com/design/([0-9A-Za-z]+)', URL.strip())`**

**Comment by RiumiToki** [comment]
> > I've mentioned a solution here. #412
> 
> Yeah, thanks. Anyway I will CopyPaste here:
> 
> **go to gui/gui.py and replace at line #48 `r'https://www.figma.com/file/([0-9A-Za-z]+)', URL.strip())` with `r'https://www.figma.com/design/([0-9A-Za-z]+)', URL.strip())`**

Did it show any error in your TkinterDesigner. When i replace it it still show an error
