### ISSUE TITLE
Generates some images but no code

### ISSUE THREAD

**Issue by mtill025** [ParthJadhav/Tkinter-Designer#47]
Hi there! Thanks for this very cool software. I'm having an issue where when I go to generate, it will get a few elements and turn them into images but does not generate any code. It doesn't grab every element either, just a handful. I tried running the exe and running from source. 

It is throwing the JSON decode error that I saw mentioned in another issue (sorry just noticed this.) Is this a Figma API issue?

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Yes @mtill025, It should have been solved by now but I don't see it's been solved. I'll check again though.

**Comment by ParthJadhav** [comment]
Also @mtill025 , Share the link to the Figma File...

**Comment by mtill025** [comment]
I tried it again this evening and it worked like a charm. So it was definitely just a Figma issue. Thanks for your help!

**Comment by ParthJadhav** [comment]
@mtill025 Nice to hear that!
