### ISSUE TITLE
It will not Generate

### ISSUE THREAD

**Issue by NoelP-YouTube** [ParthJadhav/Tkinter-Designer#63]
I'm facing an issue where it will only generate background.png, but the actual code is nowhere to be found

**Comment by ParthJadhav** [comment]
Can you share the Link to the Figma file?

**Comment by NoelP-YouTube** [comment]
I Fixed the issue, It wasn't allowing *Background* To be a Group. i am now however having an issue that now an entire file is generated. window.py does not include a mainloop. and is missing key elements

**Comment by NoelP-YouTube** [comment]
it is giving me an SyntaxError: unexpected EOF while parsing at line 41.

**Comment by NoelP-YouTube** [comment]
> Can you share the Link to the Figma file?

https://www.figma.com/file/nwOJjHnTZwrv1lWC5Vevpe/Untitled?node-id=0%3A1

**Comment by NoelP-YouTube** [comment]
Nvm, Fixed that too, now my project is not matching the Tkinter project

**Comment by ParthJadhav** [comment]
https://github.com/ParthJadhav/Tkinter-Designer/issues/62

You can take a look at last few comments... He had the same problem.

**Comment by NoelP-YouTube** [comment]
I really dont wanna be a hassle, but i do now understand what is being said here. I also think i have a different issue.
![image](https://user-images.githubusercontent.com/64641984/124358699-c6aa1980-dc21-11eb-9fe9-2e00172dbd0f.png)
Please update me, i dont mind handing out Edit Permissions :))

**Comment by ParthJadhav** [comment]
Sure, Send a link with edit permissions.

**Comment by NoelP-YouTube** [comment]
Everyone is able to edit it. Ill remove it when you're done
https://www.figma.com/file/nwOJjHnTZwrv1lWC5Vevpe/Untitled?node-id=0%3A1&frame-preset-name=Desktop

You're a real baller <3

**Comment by NoelP-YouTube** [comment]
Sent you a small Donation :))
Thanks for Helping me out. Im usually not the one that asks for help. But i kind of lost my orentation in this. Thanks again Parth

**Comment by ParthJadhav** [comment]
It's working now - 

You should not name anything which matches the element naming. Ex you named text - TextArea , Also you missed to add a rectangle behind the buttons.
Also opacity is not supported. Change the colour directly.

<img width="1458" alt="Screenshot 2021-07-03 at 8 57 22 PM" src="https://user-images.githubusercontent.com/42001064/124359137-45627f00-dc41-11eb-9c70-98d3faed5b94.png">


The button bg color is still not working, let me see.

**Comment by ParthJadhav** [comment]
> Sent you a small Donation :))
> Thanks for Helping me out. Im usually not the one that asks for help. But i kind of lost my orentation in this. Thanks again Parth

Ohh, Thanks a lot ! This would be the first donation !!

**Comment by NoelP-YouTube** [comment]
Is rounding of the rectangles supported?

**Comment by ParthJadhav** [comment]
Nope, I am adding it to background layer. So it would become image.

**Comment by NoelP-YouTube** [comment]
It depresses me that i only had 2 bucks on my paypal. Ill donate more later. I've been searching for a lookalike project like this for ages. You're a legend

**Comment by ParthJadhav** [comment]
<img width="1458" alt="Screenshot 2021-07-03 at 8 59 54 PM" src="https://user-images.githubusercontent.com/42001064/124359227-a25e3500-dc41-11eb-9641-60253c00a0dd.png">

It's working now !

**Comment by NoelP-YouTube** [comment]
I love you so darn much

**Comment by ParthJadhav** [comment]
> It depresses me that i only had 2 bucks on my paypal. Ill donate more later. I've been searching for a lookalike project like this for ages. You're a legend

Thank you so much ! I created this project for the same reason  - I was too looking for such project but didn't found. So I created one .

**Comment by NoelP-YouTube** [comment]
🤙 You're the best man! I gotta go back to devving now :))

**Comment by ParthJadhav** [comment]
Yuup ! Happy Devving 😉☄️

**Comment by NoelP-YouTube** [comment]
Small question, It's not showing everything for me. I guess it's TKinter itself 
![image](https://user-images.githubusercontent.com/64641984/124359364-e5f67600-dc24-11eb-8fa8-be0cd7c52a3e.png)

**Comment by ParthJadhav** [comment]
Ohh, It should not happen ...

**Comment by NoelP-YouTube** [comment]
Let's try on RDP

**Comment by ParthJadhav** [comment]
Let me check again, Also 1 more thing - The font size in widows and linux is greater compared to figma. We need to adjust that manually...

**Comment by ParthJadhav** [comment]
RDP means ?

**Comment by NoelP-YouTube** [comment]
Remote Desktop, I run Windows. Same thing on RDP. But *your* Program runs perfectly fine. Ideas?

**Comment by ParthJadhav** [comment]
Oh, I guess you were not using the latest version of Tkinter Designer. There was a problem where the X and Y coordinates of the frame should be 0. In our case it were not 0.

**Comment by ParthJadhav** [comment]
Give it a try now...

**Comment by NoelP-YouTube** [comment]
I feel so retarded. It works now. All i had to do is redownload your tool

**Comment by NoelP-YouTube** [comment]
Sorry for the inconvienence! Keep on working on this project, It's gonna be amazing

**Comment by ParthJadhav** [comment]
😅 NP, Also if you are going to donate next time then use buymeaCoffee, Paypal took the quarter of the amount as fee 😅

**Comment by ParthJadhav** [comment]
Closing this issue, Reopen if you have any problem.
