### ISSUE TITLE
Rectangles missings in code 

### ISSUE THREAD

**Issue by Abdulrehman-PIAIC80387** [ParthJadhav/Tkinter-Designer#66]
i make a design but when i convert it into code some elements specially rectangle will disappear...
i tried multiple times but failed to generate. please help
regards.

https://www.figma.com/file/2QRx53BUWoXXrzW1CtUjlD/Untitled?node-id=1%3A4

**Comment by ParthJadhav** [comment]
I don't have access to my pc, I'll take a look tomorrow. 

Thanks!

**Comment by ParthJadhav** [comment]
<img width="281" alt="Screenshot 2021-07-07 at 10 11 41 AM" src="https://user-images.githubusercontent.com/42001064/124701172-bb9a0680-df0b-11eb-85c0-4e36dad60234.png">

Hey @Abdulrehman-PIAIC80387 , I saw the file and saw that the elements are not named correctly.

Images :-
Clone the latest version of tkinter Designer and name all the images as "Image" dont add anything else in the name. 

Buttons :- 
The buttons did not have a background matching the the colour of the background resulting in unrounded buttons.

I have made the changes in this file -> 
https://www.figma.com/file/0KjvTkUGPGPACFtrFwcfCR/Untitled-(Copy)?node-id=0%3A1 

You can duplicate this file to make your own changes. Or use it directly.

**Comment by Abdulrehman-PIAIC80387** [comment]
Yes, it worked , Thanks alot mate. 
Regards

**Comment by ParthJadhav** [comment]
Nice ! Closing this issue open if any problems occur
