### ISSUE TITLE
Text Element: positional errors dependent on font size and dimensions of Figma text bounding box

### ISSUE THREAD

**Issue by neilbaldwin** [ParthJadhav/Tkinter-Designer#68]
Platform: Mac OSX 10.15.7, Python 3.9.5

I see from the code that Figma must use the center of a text element as it's origin because you're doing this calculation in 'backend.py' to modify the X:Y cordinate when setting the position on the Tkinter Canvas:

            x, y = x + (width / 2), y + (height / 2)

But depending on the font size and depending on the dimensions of the Figma bounding box, this results in an X:Y error in the generated code. I guess this is probably unique to Text elements as in Figma you can set the bounding box to greater than the space taken up by the actual text.

Example where Figma Text bounding boxes are as small as possible without pusing the text onto new lines.

Screenshot from Figma:
![Screenshot 2021-07-08 at 13 29 39](https://user-images.githubusercontent.com/4408530/124921954-e5792900-dff0-11eb-8883-2c5afcf7e696.png)

Screenshot from generated window.py
![Screenshot 2021-07-08 at 13 31 47](https://user-images.githubusercontent.com/4408530/124922209-2f620f00-dff1-11eb-9d7d-45c1f74cf214.png)

**Comment by ParthJadhav** [comment]
Yes, I agree with you @neilbaldwin . The change we can do is instead of calculating the centre we will directly use top left as they are default alignment in Figma...

what do you think @neilbaldwin ?

**Comment by neilbaldwin** [comment]
Hi @ParthJadhav - thanks for the quick response.

Yes, I agree, it's probably a safer way to calculate the coordinates from the top-left.

(Thank you for creating this project, it's a brilliant idea and works really well if you're a Figma user!)

**Comment by ParthJadhav** [comment]
> (Thank you for creating this project, it's a brilliant idea and works really well if you're a Figma user!)

Thanks !

>  Yes, I agree, it's probably a safer way to calculate the coordinates from the top-left.

I tried it but it doesn't work -> 

Figma Screenshot :-
![Screenshot 2021-07-08 at 6 31 53 PM](https://user-images.githubusercontent.com/42001064/124926116-c7c0b980-e01a-11eb-98a8-bda5e5187d77.png)

Created code :- 
<img width="461" alt="Screenshot 2021-07-08 at 6 31 38 PM" src="https://user-images.githubusercontent.com/42001064/124926077-be375180-e01a-11eb-8e7b-5d41d5e572fd.png">

And now I remember, when creating the project I used it directly and but it didnt work. So I tried the centre approach.

**Comment by neilbaldwin** [comment]
Yes, I've just been experimenting myself. It seems really odd the way Tkinter/Canvas is handling coordinates for .create_text.

See image. That's two strings using the same font and font size placed on the same X coordinate. It looks like Tkinter is placing the center of the string at the specified coordinates which I can now see why you performed the calculation and modification.

It would seem that the way around it would be to place the Text widget (in Tkinter) and once it's on the Canvas, interogate the object to determin the pixel width and then use this as part of the calculation to determin the Canvas coordinates. I'm trying to figure out if it's possible to return the Width and Height values of the Text widget after it's been created but so far I haven't found the answer.

**Comment by neilbaldwin** [comment]
Ah, I understand a little more now.

Tkinter/Canvas uses the center of 'objects' when placing them at an X:Y position on the canvas (I hadn't noticed that you use the same width/height divided by 2 modification on all elements).

This works with elements that are of a definite pixel dimension bu the pixel dimension of a Text element as reported by Figma does not necessarily reflect the absolute pixel size of the text as it's rendered by Canvas.

I did some tests and doing canvas.create_text definitely renders differently than if you added a regular Label to the canvas. However the regular Tk.Label widget also includes a background colour etc. so you couldn't replace the canvas.create_text so simply.

One way around it would maybe to treat Text elements in the same way you handle Buttons: place the text on top of a coloured rectangle and ground the rectangle and text togehter for processing by your tool? Probably not ideal but I can't see a way around it otherwise.

**Comment by ParthJadhav** [comment]
We could do that but it would make the creation of Design more complex and time consuming. I want to remove that button background thing too. 

I found a setting which makes the bounding box's size similar to the text. - 
![Screenshot 2021-07-08 at 7 38 16 PM](https://user-images.githubusercontent.com/42001064/124936401-22124800-e024-11eb-9343-651c13d7d52e.png)

Now I want  to figure out a way by which it will automatically be applied while parsing. Other way could be adding this step in instructions but I would like if it's automatic. 
I am going to post a question on Figma Forum on how can we do that while making the API Call.

**Comment by neilbaldwin** [comment]
Cool, hopefully that would work. The other quirk is that if you change the font size in Figma then it affects the rendered size on the Canvas and so affects the placement.

**Comment by neilbaldwin** [comment]
I was also playing around with just using tk.Label and setting the Label background colour the same as the canvas colour like this:

text = Label(
    canvas,
    text='12345678',
    background=canvas['bg'],
    foreground='#FFF'
)
text.place(x=20,y=70)

That works but only if the text is placed directly onto the canvas.

**Comment by ParthJadhav** [comment]
Yes, That's the reason I switched to Canvas Text.

**Comment by neilbaldwin** [comment]
> Yes, That's the reason I switched to Canvas Text.

Haha, I've arrived where you got to already! :)

**Comment by ParthJadhav** [comment]
https://forum.figma.com/t/get-actual-coordinates-of-text-instead-of-bounding-box/5529

**Comment by neilbaldwin** [comment]
Ah! I might have a workaround :)

```
canvas.create_text(
    20,20,
    text = "12345678",
    fill = "#ffffff",
    font = ("ArialMT", int(14.0)),
    anchor='w'
)

canvas.create_text(
    20,40,
    text = "1",
    fill = "#ffffff",
    font = ("ArialMT", int(18.0)),
    anchor='w'
)

```
Setting the 'anchor' property to 'w' causes the location point to be on the left side of the text element and it lines up the text correctly regardless of the font size.

**Comment by ParthJadhav** [comment]
WHAT ! Was it that simple ? I was creating calculations to have it at place using it's alignment properties of text. 

```
if text_alignment == ('LEFT', 'TOP'): #Done
     x, y = x + (width / 2), y + (height / 2)
elif text_alignment == ('CENTER', 'CENTER'): #Done
    width, height = get_dimensions(element)
    x, y = x + (width / 2), y + (height / 2)
elif text_alignment == ('CENTER', 'TOP'): 
    width, height = get_dimensions(element)
    x, y = x + (width / 2), y
```

**Comment by neilbaldwin** [comment]
Well, my 'solution' is dependent on you having your Figma text aligned to the left of the text bounding box, which might not be the case for everyone's particular project but it seems like a way forward at least!

**Comment by ParthJadhav** [comment]
Oh wait, The text is aligned default to CENTER, TOP

**Comment by neilbaldwin** [comment]
It looks like by default it's set to "anchor='center'"

**Comment by ParthJadhav** [comment]
No, It's default to top left. So we are safe.

**Comment by ParthJadhav** [comment]
> It looks like by default when placing the text on the Canvas, it's set to "anchor='center'"

Yes ! That's true. But in Figma it's top left. But after changing anchor="nw" it becomes similar to Figma as you said.

**Comment by neilbaldwin** [comment]
OK so how do I make this fix to the latest commit version? I've changed the code on my local version and verified it works.

I'm a bit of a novice with git (apart from with my own projects).

**Comment by ParthJadhav** [comment]
Yes, Let me check again and I'll let you know.

**Comment by ParthJadhav** [comment]
Clone the latest repository and make this change in Tkinter-Designer/figma/custom.py

![Screenshot 2021-07-20 at 10 47 14 AM](https://user-images.githubusercontent.com/42001064/126265818-0be13798-3639-4b4a-9b3e-92ecb9a3cb97.png)

**Comment by jrobchin** [comment]
Is @neilbaldwin going to make a PR for this issue?

**Comment by ParthJadhav** [comment]
Yes.

**Comment by neilbaldwin** [comment]
He is when he can figure out how to do that 😊

**Comment by neilbaldwin** [comment]
I think I've done it. Apologies if I haven't striclty followed protocol, this is my first time contributing anything to someone elses code 🙂

**Comment by jrobchin** [comment]
No that's great, just wanted to make sure it was being addressed :)

**Comment by ParthJadhav** [comment]
Yeah, No problem. Thanks for coming up with this brilliant solution.

**Comment by saur0x** [comment]
Support for other anchor points can be added later. It's top-left in Figma by default and `nw` anchor handles that case.

**Comment by ParthJadhav** [comment]
Yup !
