### ISSUE TITLE
CI - Testing and Packaging for Multiple Platforms

### ISSUE THREAD

**Issue by jvendegna** [ParthJadhav/Tkinter-Designer#69]
Okay, let's begin. For reference Parth asked me for assistance with CI on some other forum.

### Testing

Looking at the code for the backend, the first task which comes to mind is to create a boilerplate design we can use in an automated test suite. We could use the design for the Tkinter-Designer UI itself, but something more comprehensive would be desirable long term. Something which uses as many if not all available elements as possible. Once a design is chosen, we'll know what we can assert and can start writing tests. Then we plug in the Action to run pytest. Once these tests are in place there should be no way to merge into master without them passing.

### Packaging

In terms of packaging, automating a macos package is going to be a pain. Windows shouldn't be. I think we can use py2exe to handle that in an Action. And the tarball works well for linux... desktop linux users don't typically need their hand held. But honestly I am over here wondering: why bother with this phase? Automated testing should be enough to ensure cross platform functionality. But as python would be a prerequisite no matter what, why not let the user install and use in whatever method they preference. For example, on windows I'd just create a batch file like:

```
@echo off
"C:\Path\to\python.exe" "C:\Path\To\Script"
pause
```

Then maybe clutter my desktop with a shortcut to the batchfile and change the icon. 

on Linux I'd just create an alias or symlink

on Mac I'd either alias if I used it daily, or just run the python command to start it up. Dragging something into the application menu just doesn't matter to me.

I am not saying there is no use for packaging these the hard way. But I am saying that I am just one user who happens to work on all three platforms, and those are my personal preferences for each. I'm sure others opinions differ.

@ParthJadhav thoughts?

**Comment by ParthJadhav** [comment]
Hey @jvendegna, Thanks for considering to help. 

### Testing :
It is almost certain that this PR  https://github.com/ParthJadhav/Tkinter-Designer/pull/67 would be merged into master and it would make writing tests easier.  

Yes, We should create a design which would take into account all the elements.

### Packaging :
> But honestly I am over here wondering: why bother with this phase?

I think you are right, there's very short amount of people who have downloaded the packaged release compared to clones. Also the windows mark unsigned executables as virus hence preventing users from downloading it. While in MacOS it's really a hassle.

**Comment by jvendegna** [comment]
Sweet. I'll follow #67 and wait for the merge. Then get to writing some tests. Thanks for the quick reply!

**Comment by ParthJadhav** [comment]
Yup. Thanks for help !

**Comment by jrobchin** [comment]
With regards to packaging I think being able to install the CLI tool using pip would be very valuable.

**Comment by ParthJadhav** [comment]
Yeah, That'll save lot of time as well as it'll become easier!

**Comment by ParthJadhav** [comment]
Hey @jvendegna , The PR is merged. We should continue this from here on.

**Comment by jvendegna** [comment]
Just rolling out of bed and imbibing mass quantities of caffeine. Congrats on getting that big PR done.

Alright, I'd appreciate some help creating a design that covers all the bases. This would facilitate writing tests a lot easier.

In the meantime I'll start working on publishing the package to pypy via GH Actions (I'll use a local runner and pypy registry while developing so not to eat up build time or publish unintentionally).

Thoughts on containerization?

**Comment by ParthJadhav** [comment]
I have no idea or experience in publishing packages to pypi. I am afraid that I can't be of much help in that matter.

**Comment by jvendegna** [comment]
No worries at all. I've already got the package built locally and am just sitting back down to test it out. Doubt it'll work on the first try, but I'll report back soon with anything standing in my way.

**Comment by ParthJadhav** [comment]
Awesome! Nice to hear that.

**Comment by jvendegna** [comment]
Hey, forgive me. I'm typically the owner of an entire org's repos/projects and don't face permission issues often. I also work in GitLab and BitBucket . Is a fork necessary, or can I push a branch up here? Currently I don't have permission to push a branch. LMK what you prefer.

I've got two commits ready to go, but I just branched out from this repo. I can recreate in a fork if necessary, nbd.

**Comment by ParthJadhav** [comment]
Closing this since we've achieved the goal :)
