### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by Code-py007** [ParthJadhav/Tkinter-Designer#71]
When I generate the file , I get this error:
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\----------\anaconda3\envs\NewsAndWiki\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\----Path------\Tkinter-Designer\tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\----Path------\Tkinter-Designer\backend.py", line 220, in generate_code
    bg = get_color(element)
  File "C:\----Path------\Tkinter-Designer\backend.py", line 9, in get_color
    el_r = element["fills"][0]["color"]['r'] * 255
IndexError: list index out of range`

**Comment by ParthJadhav** [comment]
Can you share the link to your Figma file?

**Comment by Code-py007** [comment]
here you go: https://www.figma.com/file/Oa2qKu7iFRbETtBBbLyGdd/Untitled?node-id=0%3A1

**Comment by ParthJadhav** [comment]
It's with or without those elements?

**Comment by Code-py007** [comment]
Without

**Comment by ParthJadhav** [comment]
What should I look for then 😅

**Comment by Code-py007** [comment]
can you fix it ?

**Comment by ParthJadhav** [comment]
Offcourse but if something is wrong but as you said you have fixed it...

**Comment by Code-py007** [comment]
no i haven't said that i fixed it

**Comment by ParthJadhav** [comment]
Does the link you shared still gives that error?

**Comment by Code-py007** [comment]
yes

**Comment by ParthJadhav** [comment]
Okay, let me have a look.

**Comment by Code-py007** [comment]
the naming will be wrong because i lost the original file and had to make a clone of it :(

**Comment by ParthJadhav** [comment]
Did you delete it? Because the files are auto saved in Figma...

**Comment by Code-py007** [comment]
i accidentally deleted its contents

**Comment by ParthJadhav** [comment]
Ohh, Can you rename the elements so I can check it?

**Comment by Code-py007** [comment]
ok , sure

**Comment by ParthJadhav** [comment]
Also drop shadows aren't supported

**Comment by Code-py007** [comment]
alternative:  save the file as png and apply the image to the entire tkinter window and then overlap the image with the desired elements

**Comment by Code-py007** [comment]
is there any solution or should i close the issue ?

**Comment by ParthJadhav** [comment]
1. If the rectangles in front of search text is a entry then name it TextBox.

2. If you want drop shadows then name the rectangle as Image (If you are using the latest version of tkinter designer )

**Comment by Code-py007** [comment]
There are no rectangles in front of search entry

**Comment by ParthJadhav** [comment]
<img width="559" alt="Screenshot 2021-07-09 at 10 25 01 PM" src="https://user-images.githubusercontent.com/42001064/125112258-8d334b80-e104-11eb-9580-cc356f8d14a4.png">

**Comment by Code-py007** [comment]
ohh..

**Comment by Code-py007** [comment]
One last thing , when will you add Listbox support ??

**Comment by ParthJadhav** [comment]
>can you fix it ?
I fixed it for you :-  https://www.figma.com/file/aF6LBEKhwrgLTDap6d47Bw/Untitled-(Copy)?node-id=0%3A1

> One last thing , when will you add Listbox support ??
https://github.com/ParthJadhav/Tkinter-Designer/issues/70

**Comment by Code-py007** [comment]
Thank you so much 🙌 (¬‿¬)

**Comment by ParthJadhav** [comment]
Cool 👍🏻 closing it, feel free to reopen.
