### ISSUE TITLE
IndexError related to the used colours?

### ISSUE THREAD

**Issue by LumpYBoy** [ParthJadhav/Tkinter-Designer#72]
Hey, 
i'm currently facing some problems with the tkinter-designer backend file. 
I used it once and it worked. But then i gave it another try and i always get the following error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "/home/mattesbuerk/Repos/Tkinter-Designer/backend.py", line 158, in generate_code
    element_color = get_color(element)
  File "/home/mattesbuerk/Repos/Tkinter-Designer/backend.py", line 9, in get_color
    el_r = element["fills"][0]["color"]['r'] * 255
IndexError: list index out of range
`
The script always creates the folder generated_files but without any files in there.
I tried commenting out everything which is related to el_r (red colour?) in backend.py. But then the same error appears with el_g. 
Do i need to change my colours or is that a bug in the script?

Thank you very much in advance!

**Comment by ParthJadhav** [comment]
This error occurs if a element is named wrong or the naming is misplaced. Check the naming again. 

Probably because of you named a text - "TextArea".

It's most common error.

**Comment by ParthJadhav** [comment]
Can you also share link to the Figma file?

**Comment by LumpYBoy** [comment]
Sure, there you go:
https://www.figma.com/file/mniHlS9Ez41RW6olG6U0FP/Update-Manager?node-id=0%3A1

**Comment by ParthJadhav** [comment]
It's strange... There are no mistakes in the design and also one more issue with the same issue has been reported. I am currently try to figure out the problem give me some time.

**Comment by ParthJadhav** [comment]
<img width="1440" alt="Screenshot 2021-07-09 at 6 47 38 PM" src="https://user-images.githubusercontent.com/42001064/125083551-2c951600-e0e6-11eb-9cc1-aaeb5b3aabb2.png">


What a sneaky mistake 😅 You added a line below the Update Manager Text which does not have a Fill, it just has a stroke. But since you named it Rectangle Tkinter Designer wanted to look for it's fill colour which it did not have hence causing the error. 

I have fixed it. 

Also some more things :-
1. Font size would be larger in windows. It would make the interface ugly please reduce it.
2. Rounded rectangles are not supported.

**Comment by ParthJadhav** [comment]
Also this issue https://github.com/ParthJadhav/Tkinter-Designer/issues/71 was created at the same time and is same as yours. Did you created them both ?

**Comment by LumpYBoy** [comment]
Awesome! Thank you very much. I will test the solution as soon as possible.
No, #71 was created by someone else. I was surpised too.

**Comment by Code-py007** [comment]
I created #71 , this issue(#72) was created around 20 min after I posted #71.

**Comment by ParthJadhav** [comment]
Oh @Code-py007 , Let's solve yours 😃

**Comment by Code-py007** [comment]
idk why but when i removed the two rounded rectangles which served as entry widgets, it worked fine 😕

**Comment by ParthJadhav** [comment]
Were they grouped? @Code-py007

**Comment by ParthJadhav** [comment]
Wait let's talk on your issue page, I don't want to disturb @LumpYBoy with unnecessary notifications 😄
