### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Johnny-Five1982** [ParthJadhav/Tkinter-Designer#74]
After installing and going through the video and written instructions and running the application it gave this error. The items on figma are carefully labeled. What could be the problem?

### Installation
```
py -m venv env
.\env\Scripts\activate
where python
git clone https://github.com/ParthJadhav/Tkinter-Designer
cd Tkinter-Designer
pip3 install -r requirements.txt
py tkinter_designer.py
```

### **Error Message**
    window_elements = fig_window["children"]
    KeyError: 'children'

**Comment by ParthJadhav** [comment]
Yes @Johnny-Five1982 everything is right except you missed one thing - you didn't create a frame.

Press F and create a frame around all elements. It's like Tkinter Window.

**Comment by Johnny-Five1982** [comment]
Thanks! Got it to work now. Your doing a great job with this! Keep it up!

**Comment by ParthJadhav** [comment]
Nice to hear that , Thanks @Johnny-Five1982  !
