### ISSUE TITLE
Not Opening through Terminal

### ISSUE THREAD

**Issue by kabin-space** [ParthJadhav/Tkinter-Designer#75]
@ParthJadhav 
![issuess](https://user-images.githubusercontent.com/86792753/125653377-0e30da43-e2a7-4aca-a1c3-e4277e3eb508.PNG)

**Comment by ParthJadhav** [comment]
You need to install the requirements first. 

pip3 install -r requirements.txt

**Comment by kabin-space** [comment]
I followed every steps but still it dose not work
![issuessss](https://user-images.githubusercontent.com/86792753/125658049-b8aeaf2c-4034-4248-806a-3360ad9f67b1.PNG)

**Comment by ParthJadhav** [comment]
Can you try pip instead of pip3 and python instead of python3. It works sometimes.

**Comment by kabin-space** [comment]
Thank you so much, this time it worked. I can finally bring this to life!
![Uploading cnvgsddf.PNG…]()

**Comment by ParthJadhav** [comment]
Awesome ! I can't see the Image though 😄

**Comment by kabin-space** [comment]
Just updated image, does it show up now?

**Comment by ParthJadhav** [comment]
Woah ! That looks Great. Feel free to open a issue if any problem arises while converting the design, I really like it 😄
