### ISSUE TITLE
File Not generated

### ISSUE THREAD

**Issue by Akashj13** [ParthJadhav/Tkinter-Designer#82]
I have cloned the repository and when trying to generate the files. In the build file there is only an asset folder with nothing in it.

**Comment by ParthJadhav** [comment]
Can you share the link your Figma file?

**Comment by Akashj13** [comment]
Ohh really sorry there was a small mistake on my part. Now that the file is created, it is misplaced.
Figma Link: https://www.figma.com/file/74rVSDyvNkp0DQSLeWUGIY/GUI?node-id=1%3A4
![image](https://user-images.githubusercontent.com/66905467/126206388-483575ab-5165-42b2-9ab1-02f9c316d426.png)

**Comment by Akashj13** [comment]
I tried some maneuvers like changing colour, etc. but still the interface is showing distorted like shown above

**Comment by ParthJadhav** [comment]
Hey @Akashj13 the solution is simple. You have missed to add frame around the elements. Press F and create a frame.

**Comment by Akashj13** [comment]
Really sorry, but I tried to reinstall the file through cloning, and an error is popping hope you could help with the same.
![image](https://user-images.githubusercontent.com/66905467/126272838-1a5dcefb-7d2d-4d84-a1e8-851d8d5c4656.png)

**Comment by ParthJadhav** [comment]
The instructions have changed from yesterday’s update. Please refer to new instructions.

**Comment by Akashj13** [comment]
Ohh thanks, opened the designer but no file was generated

**Comment by ParthJadhav** [comment]
Did you add the frame?

**Comment by Akashj13** [comment]
![image](https://user-images.githubusercontent.com/66905467/126274611-7db9d4c4-44d6-4e8f-bea3-9575e7169de4.png)

**Comment by Akashj13** [comment]
I have no issues in giving edit access to check if something's wrong. 
https://www.figma.com/file/74rVSDyvNkp0DQSLeWUGIY/GUI?node-id=0%3A1

**Comment by Akashj13** [comment]
Should I group all the elements together as well?

**Comment by ParthJadhav** [comment]
Give me some time, I am checking.

**Comment by ParthJadhav** [comment]
Is it working now ?

**Comment by Akashj13** [comment]
No it isn't, though its somewhat better than before
![Uploading image.png…]()

**Comment by Akashj13** [comment]
![image](https://user-images.githubusercontent.com/66905467/126333190-7bfc7914-22e3-4d43-8a8a-93a092e8d03a.png)
I rescaled it so the output came as this

**Comment by ParthJadhav** [comment]
Yes, I forgot to tell - the font size is usually higher in. Windows.

**Comment by Akashj13** [comment]
Ohh thanks a lot, it's working now. BTW Great initiative as Tkinter by nature is quite unattractive.

**Comment by ParthJadhav** [comment]
Yes, That was the reason to create Tkinter Designer.

Thanks!
