### ISSUE TITLE
Need an API key from Pypi in repo secrets

### ISSUE THREAD

**Issue by jvendegna** [ParthJadhav/Tkinter-Designer#86]
Someone needs to be responsible for receiving communications from pypi regarding package releases. Typically this is the repo owner or an active maintainer.
You're also required to supply an api token when publishing a package. So we cannot publish a package without this.

Discussion can take place here as to who if not ParthJadhav, but to close this out:

* Sign up for a pypi account.
* Create an API Key in your account settings
* Store it in repo secrets as PYPI_API_TOKEN

**Comment by ParthJadhav** [comment]
Sure, I'll be the maintainer for the package. I'll create the account soon and also add the api key.

**Comment by ParthJadhav** [comment]
Added the key to repo secrets... Can you test it ?

**Comment by jvendegna** [comment]
> Added the key to repo secrets... Can you test it ?

I am struggling with that. This is a pre-built workflow and one I know works as I've used it elsewhere. But I've pushed a change to my PR branch which should have triggered a build, and it did not. [See commit](https://github.com/ParthJadhav/Tkinter-Designer/pull/84/commits/5c6dd4516bd95a06704f93d1c923debcd875a0df) Could be a permissions issue, could be configuration, could be that the workflow needs to exist on the main branch. I'm not exactly sure how to test this, but I want to test it before we merge if at all possible.

**Comment by ParthJadhav** [comment]
I saw the GH Action failed workflow and it stated that the Token didnt start with "pypi" and it must be that you have entered the below part of the token. 

It confused me too. It was like :- 

```
pypi-
14njlfenql1i3;13nfq3;kngf
```

First I was going to insert the lower part but then I read somewhere that we need to include "pypi" too. You can remove the old token and generate a new one and paste it with "pypi"

**Comment by jvendegna** [comment]
I don't have access to the project settings to be able to supply anything like that. What I can do is update the syntax on the workflow file. If the secret you saved includes the "pypi-", that's all I need to get it working. Also, which versions of python should this project work with?

**Comment by ParthJadhav** [comment]
Yes, I included the key in the repo secrets and also saw your commit. And it's correct the previous way...

**Comment by ParthJadhav** [comment]
`password: ${{ secrets.PYPI_API_TOKEN }} `

This the ideal way if the key is right.

**Comment by jvendegna** [comment]
I'll change it back and trigger a build now.

**Comment by ParthJadhav** [comment]
Sure, Thanks!

**Comment by jvendegna** [comment]
Build failed, same warning. I'll continue to work on the workflow in the meantime and when the stars align it'll pass.

**Comment by ParthJadhav** [comment]
It must need the API secret on your fork...

**Comment by jvendegna** [comment]
OMG, these builds are running on my fork. Okay, so yeah I do need the secret. I cannot generate an api key for pypi for your account. I don't know how you want to approach this, but I'm open to suggestions. I have keybase. If you want to message me the API key I could insert it into my repo, and you could rotate the secret. That's about the best I can come up with.

**Comment by ParthJadhav** [comment]
You can also provide me with edit permission I guess, So I can add the key.

**Comment by jvendegna** [comment]
perfect. one min.

**Comment by ParthJadhav** [comment]
Nope, I guess it only gives push access. NVM, where can I share the key to you privately ?

**Comment by jvendegna** [comment]
Yeah, that's a really poor implementation of collaborator permissions on user account owned repos. Makes multiple maintainers hard. 
I'd suggest keybase. I'm @jakevendegna there. 
If you're going to rotate it and you're not overly worried about it you could just email it to me. me@jakobvendegna.dev

**Comment by ParthJadhav** [comment]
Sure, It will be there in few minutes.

**Comment by jvendegna** [comment]
Oi! https://pypi.org/project/tkdesigner/0.1.1rc0/ 🌮 🎉

**Comment by ParthJadhav** [comment]
That's great!!!
