### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by jaiveertalwar** [ParthJadhav/Tkinter-Designer#88]
It doesn't work at all.   I run: `python -m tkdesigner.cli https://www.figma.com/file/hOTGu8P89l19ro8EbsKe2U/Sign-In-Form-Tkinter-Example-Community token -f`

It says could not find module 'tkdesigner'.   So I ran `pip3 install tkdesigner`.   That was on Python 3.7, it said: (i tried the same on 3.10, 3.9 and 2.7)

```
ERROR: Could not find a version that satisfies the requirement tkdesigner (from versions: none)
ERROR: No matching distribution found for tkdesigner
```
Please help.  Also I'm on MacOS Big Sur.

**Comment by jvendegna** [comment]
[The instructions](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#2-install-tkinter-designer) are fairly clear, and I am working on packaging as we speak. See #84. The ability to `pip install` is coming very soon. In the meantime you need to clone the project and install the requirements file to invoke the cli.

**Comment by saur0x** [comment]
1. `git clone https://github.com/ParthJadhav/Tkinter-Designer.git`
2. `cd Tkinter-Designer`
3. `python -m tkdesigner.cli -f https://www.figma.com/file/hOTGu8P89l19ro8EbsKe2U/Sign-In-Form-Tkinter-Example-Community 212473-d3e203e8-8bd5-4ec3-b9bb-82be2b7d759d`

PS. Don't share your Figma token publicly.

**Comment by jaiveertalwar** [comment]
> 1. git clone https://github.com/ParthJadhav/Tkinter-Designer.gi

I get this error:```
 jaiveertalwar@Jaiveers-Macbook-Pro-1 SpamrV2 % git clone https://github.com/ParthJadhav/Tkinter-Designer.git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
jaiveertalwar@Jaiveers-Macbook-Pro-1 SpamrV2 % 


```

**Comment by ParthJadhav** [comment]
Oh, That might be problem with command line tools. You can reinstall tool from here :- 

https://stackoverflow.com/questions/9329243/how-to-install-xcode-command-line-tools

**Comment by ParthJadhav** [comment]
Hey @jaiveertalwar Is the problem solved ?

**Comment by jaiveertalwar** [comment]
Yes thanks
