### ISSUE TITLE
Add a consistent element naming scheme

### ISSUE THREAD

**Issue by saur0x** [ParthJadhav/Tkinter-Designer#89]
The supported elements are identified using their Figma element names. For example, `Button` for a Button element and `Image` for `Canvas.Image` element. But these names are too verbose in their type, and each element of same type ends up with the same names which can cause confusion to the users.

Users should be allowed to name their elements freely like `login button`, but that's not great for element type detection.

Therefore, I propose having a consistent naming scheme like `btn login` or `img_wallpaper` for elements and the type can be deduced from the start of name. The id (`btn`, `img`) of each type is small and thus isn't overly verbose, and it allows users to instead give their elements helpful and descriptive names.

**Comment by saur0x** [comment]
It's a very small change but I would like to get other's opinions on this matter before making a PR. It would be great if you all can suggest what the type ids like `img`, `btn`, `entry` etc for each type should be.

**Comment by ParthJadhav** [comment]
I am not in favour of that. User's already confused by the naming and usually make mistakes. 
But that's my point of view.  I am always open for discussions.

Also, We can have an other way which the experimental branch is using. It uses a plugin called figma low code which added the support for Tkinter Designer. It allows users to select the type of element and skip the naming part. User's can also use the normal naming if they wish.

**Comment by jrobchin** [comment]
I like the plugin idea - I think that elements should be named as desired and there should be some metadata that describes it's type. I have yet to try it myself though.

**Comment by saur0x** [comment]
Adding plugins will add one more dependency and all the users must have it in order to use `tkdesigner`. It adds extra complexity for the users that's really not needed.
Names can describe the element type, it's easier and simpler for the users and that's the convention for Tkinter as well, `btn_submit` for example.

**Comment by ParthJadhav** [comment]
It's the matter of choice. The users would still be able to use the normal naming scheme. But in addition to that they would also be able to use the plugin if they wish.

**Comment by saur0x** [comment]
> It's the matter of choice. The users would still be able to use the normal naming scheme. But in addition to that they would also be able to use the plugin if they wish.

What do you mean the normal naming scheme? @ParthJadhav

**Comment by ParthJadhav** [comment]
Normal - Where we differentiate elements using their names.
Plugin - Where we differentiate elements using their Plugin Data.

Both can be used...

**Comment by saur0x** [comment]
I was just suggesting have some sort of token in element names instead of considering entire name as the token. For example, an element must be named `Button` in order for it to be a button. That leaves no room for being descriptive about the elements.
My suggestion was using a short token like `btn` in front of names, so the name can be `btn submit form`. The name is both descriptive and functional now. We can check for it using `if name.lower().startswith("btn"):`, and similar for other elements.

Element | Token
:---:|:---:
Rectangle | `rect` 
Entry or TextEntry| `ent`
Text | `txt`
Button | `btn`
Image | `img`

Some examples of element names: `img window background`, `txt about me`, `ent get username`.
Also, the tokens are case insensitive.

**Comment by ParthJadhav** [comment]
I guess you are right with the change. 

But we can still have the plugin... It would provide even more flexibility.

**Comment by Divyansh18186** [comment]
I am having problem with the images they don't show in output. Also elements formatting and position of on or below some elements were the ones which has tired me of using the tool.
