### ISSUE TITLE
Issue with Input Text bar

### ISSUE THREAD

**Issue by Harish3055** [ParthJadhav/Tkinter-Designer#92]
I have the below issue on converting a Tkinter application which is designed using Figma 
Original Image
![image](https://user-images.githubusercontent.com/55819957/126903500-7ee09c2a-92e2-48a7-bc37-585b3915e78c.png)
Issue
![image](https://user-images.githubusercontent.com/55819957/126903526-c36b7826-9a92-47fa-ab50-6cc0868bfde8.png)

**Comment by ParthJadhav** [comment]
Can you share a link to your Figma file?

**Comment by Harish3055** [comment]
@ParthJadhav Sure this is the url :- https://www.figma.com/file/UKaEfJW50Vq4mwsXOr34oT/Untitled?node-id=0%3A1

**Comment by ParthJadhav** [comment]
Hey, Add a frame around your design by pressing F. This will serve you as a Figma window.

**Comment by ParthJadhav** [comment]
You can't add text above TextArea... if you want then you need to tweak a little with the generated design.

**Comment by ParthJadhav** [comment]
@Harish3055 You can close this if it's solved.

**Comment by Harish3055** [comment]
@ParthJadhav It worked.
